// src/pages/SignUp/SignUp.jsx
import { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext.jsx'
import './SignUp.css'

export default function SignUp() {
  const { signup } = useAuth()
  const navigate = useNavigate()

  const [form, setForm] = useState({ fullName: '', email: '', password: '', confirmPassword: '' })
  const [touched, setTouched] = useState({})
  const [errorMessage, setErrorMessage] = useState('')
  const [isLoading, setIsLoading] = useState(false)

  const errors = {}
  if (form.fullName.trim().length < 3) errors.fullName = 'Name must be at least 3 characters.'
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) errors.email = 'Valid email is required.'
  if (form.password.length < 6) errors.password = 'Password must be at least 6 characters.'
  if (!form.confirmPassword) errors.confirmPassword = 'Please confirm your password.'

  const handleChange = (e) => setForm(prev => ({ ...prev, [e.target.name]: e.target.value }))
  const handleBlur = (field) => setTouched(prev => ({ ...prev, [field]: true }))

  const handleSubmit = (e) => {
    e.preventDefault()
    setTouched({ fullName: true, email: true, password: true, confirmPassword: true })
    if (Object.keys(errors).length > 0) return

    if (form.password !== form.confirmPassword) {
      setErrorMessage('Passwords do not match.')
      return
    }

    setIsLoading(true)
    setErrorMessage('')
    setTimeout(() => {
      signup(form.fullName, form.email)
      setIsLoading(false)
      navigate('/')
    }, 1000)
  }

  return (
    <div className="signup-wrapper d-flex align-items-center justify-content-center">
      <div className="signup-card">
        <h2 className="title">Create Account</h2>
        <p className="subtitle">Start your journey with ELEVÉ today.</p>

        <form onSubmit={handleSubmit} noValidate>
          <div className="form-group mb-4">
            <label htmlFor="signup-name">Full Name</label>
            <input type="text" id="signup-name" name="fullName" value={form.fullName}
              onChange={handleChange} onBlur={() => handleBlur('fullName')} placeholder="Your full name" />
            {touched.fullName && errors.fullName && <div className="text-danger small mt-1">{errors.fullName}</div>}
          </div>

          <div className="form-group mb-4">
            <label htmlFor="signup-email">Email Address</label>
            <input type="email" id="signup-email" name="email" value={form.email}
              onChange={handleChange} onBlur={() => handleBlur('email')} placeholder="your@email.com" />
            {touched.email && errors.email && <div className="text-danger small mt-1">{errors.email}</div>}
          </div>

          <div className="form-group mb-4">
            <label htmlFor="signup-password">Password</label>
            <input type="password" id="signup-password" name="password" value={form.password}
              onChange={handleChange} onBlur={() => handleBlur('password')} placeholder="Min. 6 characters" />
            {touched.password && errors.password && <div className="text-danger small mt-1">{errors.password}</div>}
          </div>

          <div className="form-group mb-4">
            <label htmlFor="signup-confirm">Confirm Password</label>
            <input type="password" id="signup-confirm" name="confirmPassword" value={form.confirmPassword}
              onChange={handleChange} onBlur={() => handleBlur('confirmPassword')} placeholder="Repeat password" />
            {touched.confirmPassword && errors.confirmPassword && <div className="text-danger small mt-1">{errors.confirmPassword}</div>}
          </div>

          {errorMessage && <div className="error-message mb-3 text-center">{errorMessage}</div>}

          <button type="submit" className="btn-signup w-100" disabled={isLoading}>
            {isLoading ? 'Creating Account...' : 'Create Account'}
          </button>
        </form>

        <div className="text-center mt-4">
          <p>Already have an account? <Link to="/login" className="login-link">Sign In</Link></p>
        </div>
      </div>
    </div>
  )
}

// src/app/pages/sign-up/sign-up.component.ts
import { Component, ChangeDetectionStrategy, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';

@Component({
    selector: 'app-sign-up',
    standalone: true,
    imports: [CommonModule, FormsModule, RouterLink],
    templateUrl: './sign-up.component.html',
    styleUrls: ['./sign-up.component.css'],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class SignUpComponent {
    private authService = inject(AuthService);
    private router = inject(Router);

    fullName = signal('');
    email = signal('');
    password = signal('');
    confirmPassword = signal('');

    isLoading = signal(false);
    errorMessage = signal('');

    onSubmit() {
        // Basic Validation
        if (!this.fullName() || !this.email() || !this.password() || !this.confirmPassword()) {
            this.errorMessage.set('Please fill in all fields.');
            return;
        }

        if (this.password() !== this.confirmPassword()) {
            this.errorMessage.set('Passwords do not match.');
            return;
        }

        this.isLoading.set(true);
        this.errorMessage.set('');

        // Simulate network delay
        setTimeout(() => {
            this.authService.signup(this.fullName(), this.email());
            this.isLoading.set(false);
            this.router.navigate(['/']); // Redirect to home on success
        }, 1000);
    }
}

<div class="signup-wrapper d-flex align-items-center justify-content-center">
    <div class="signup-card">
        <div class="card-header text-center">
            <h2 class="title">Create Account</h2>
            <p class="subtitle">Join us for your next luxury adventure.</p>
        </div>

        <form (submit)="onSubmit(); $event.preventDefault()">
            <div class="form-group mb-4">
                <label for="fullName">Full Name</label>
                <input type="text" id="fullName" name="fullName" [ngModel]="fullName()"
                    (ngModelChange)="fullName.set($event)" placeholder="John Doe" required>
            </div>

            <div class="form-group mb-4">
                <label for="email">Email Address</label>
                <input type="email" id="email" name="email" [ngModel]="email()" (ngModelChange)="email.set($event)"
                    placeholder="john@example.com" required>
            </div>

            <div class="row g-3 mb-4">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" id="password" name="password" [ngModel]="password()"
                            (ngModelChange)="password.set($event)" placeholder="******" required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="confirmPassword">Confirm Password</label>
                        <input type="password" id="confirmPassword" name="confirmPassword" [ngModel]="confirmPassword()"
                            (ngModelChange)="confirmPassword.set($event)" placeholder="******" required>
                    </div>
                </div>
            </div>

            @if (errorMessage()) {
            <div class="error-message mb-3 text-center">
                {{ errorMessage() }}
            </div>
            }

            <button type="submit" class="btn-signup w-100" [disabled]="isLoading()">
                @if (isLoading()) {
                <span class="spinner"></span> Creating Account...
                } @else {
                Create Account
                }
            </button>
        </form>

        <div class="card-footer text-center mt-4">
            <p>Already have an account? <a routerLink="/login" class="login-link">Sign In</a></p>
        </div>
    </div>
</div>
