// src/app/pages/destinations/destinations.component.ts
import { Component, ChangeDetectionStrategy, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { DestinationsService } from './destinations.service';
import { toSignal } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-destinations',
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './destinations.component.html',
  styleUrl: './destinations.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class DestinationsComponent {
  private destinationsService = inject(DestinationsService);

  destinations = toSignal(this.destinationsService.getDestinations(), { initialValue: [] });
  searchQuery = signal<string>('');
  selectedFilter = signal<string | null>(null);
  sortOption = signal<string>('recommended'); // Default sort
  minRating = signal<number>(0);
  isSortDropdownOpen = signal<boolean>(false);
  minPrice = signal<number | null>(null);
  maxPrice = signal<number | null>(null);
  isPriceDropdownOpen = signal<boolean>(false);
  inputMinPrice = signal<number | null>(null);
  inputMaxPrice = signal<number | null>(null);

  filteredDestinations = computed(() => {
    const query = this.searchQuery().toLowerCase();
    const filter = this.selectedFilter();
    const sort = this.sortOption();
    const rating = this.minRating();
    const minP = this.minPrice();
    const maxP = this.maxPrice();
    const allDestinations = this.destinations();

    let result = allDestinations.filter(dest => {
      const matchesSearch = dest.name.toLowerCase().includes(query) ||
        dest.location.toLowerCase().includes(query) ||
        dest.description.toLowerCase().includes(query);

      const matchesFilter = filter ? dest.type === filter : true;
      const matchesRating = dest.rating >= rating;
      const matchesMinPrice = minP === null || dest.price >= minP;
      const matchesMaxPrice = maxP === null || dest.price <= maxP;

      return matchesSearch && matchesFilter && matchesRating && matchesMinPrice && matchesMaxPrice;
    });

    // Sorting Logic
    return result.sort((a, b) => {
      switch (sort) {
        case 'price-asc':
          return a.price - b.price;
        case 'price-desc':
          return b.price - a.price;
        case 'rating':
          return b.rating - a.rating; // Highest rating first
        case 'popularity':
          const popWeight = { 'High': 3, 'Medium': 2, 'Low': 1 };
          return popWeight[b.popularity] - popWeight[a.popularity];
        case 'recommended':
        default:
          // Recommended: High Popularity + High Rating
          const popScore = { 'High': 10, 'Medium': 5, 'Low': 1 };
          const scoreA = popScore[a.popularity] + (a.rating * 2);
          const scoreB = popScore[b.popularity] + (b.rating * 2);
          return scoreB - scoreA;
      }
    });
  });

  updateSearch(query: string) {
    this.searchQuery.set(query);
  }

  updateFilter(filter: string | null) {
    this.selectedFilter.set(filter);
  }

  updateSort(sort: string) {
    this.sortOption.set(sort);
    this.isSortDropdownOpen.set(false); // Close dropdown after selection
  }

  toggleSortDropdown() {
    this.isSortDropdownOpen.update(v => !v);
  }

  updateMinRating(rating: number) {
    this.minRating.set(rating);
  }

  updatePriceRange(min: number | null, max: number | null) {
    this.minPrice.set(min);
    this.maxPrice.set(max);
    this.isPriceDropdownOpen.set(false);
  }

  togglePriceDropdown() {
    if (!this.isPriceDropdownOpen()) {
      // Opening: Sync inputs with current applied values
      this.inputMinPrice.set(this.minPrice());
      this.inputMaxPrice.set(this.maxPrice());
    }
    this.isPriceDropdownOpen.update(v => !v);
  }
}

<div class="container py-5 mt-5">
    <div class="text-center mb-5 pt-4">
        <h1>Top Destinations</h1>
        <p class="lead text-muted">Explore our hand-picked locations across the globe.</p>
    </div>

    <!-- Search Section -->
    <div class="row mb-4 justify-content-center">
        <div class="col-md-6">
            <div class="input-group search-input-group shadow-sm rounded-pill overflow-hidden">
                <span class="input-group-text bg-white border-0 ps-3"><i class="bi bi-search text-muted"></i></span>
                <input type="text" class="form-control border-0 shadow-none ps-2" placeholder="Search destinations..."
                    [ngModel]="searchQuery()" (ngModelChange)="updateSearch($event)">
            </div>
        </div>
    </div>

    <!-- Filter & Sort Toolbar -->
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-center mb-5 gap-3">
        <!-- Left: Categories -->
        <div class="d-flex gap-2 flex-wrap justify-content-center">
            <button class="btn rounded-pill px-3 py-2 btn-sm-custom" [class.btn-primary]="selectedFilter() === null"
                [class.btn-outline-primary]="selectedFilter() !== null" (click)="updateFilter(null)">All</button>
            <button class="btn rounded-pill px-3 py-2 btn-sm-custom" [class.btn-primary]="selectedFilter() === 'Beach'"
                [class.btn-outline-primary]="selectedFilter() !== 'Beach'"
                (click)="updateFilter('Beach')">Beach</button>
            <button class="btn rounded-pill px-3 py-2 btn-sm-custom" [class.btn-primary]="selectedFilter() === 'City'"
                [class.btn-outline-primary]="selectedFilter() !== 'City'" (click)="updateFilter('City')">City</button>
            <button class="btn rounded-pill px-3 py-2 btn-sm-custom" [class.btn-primary]="selectedFilter() === 'Nature'"
                [class.btn-outline-primary]="selectedFilter() !== 'Nature'"
                (click)="updateFilter('Nature')">Nature</button>
            <button class="btn rounded-pill px-3 py-2 btn-sm-custom"
                [class.btn-primary]="selectedFilter() === 'Cultural'"
                [class.btn-outline-primary]="selectedFilter() !== 'Cultural'"
                (click)="updateFilter('Cultural')">Cultural</button>
        </div>

        <!-- Right: Sort & Rating -->
        <div class="d-flex gap-2 align-items-center">
            <!-- Price Filter -->
            <div class="dropdown">
                <button
                    class="btn btn-outline-primary rounded-pill px-3 d-flex align-items-center gap-2 border-0 bg-white shadow-sm"
                    type="button" (click)="togglePriceDropdown()">
                    <span class="small text-muted text-uppercase fw-bold">Price:</span>
                    <span class="fw-bold text-dark">
                        @if (minPrice() || maxPrice()) {
                        {{ minPrice() || 0 | currency:'USD':'symbol':'1.0-0' }} - {{ maxPrice() || 'Any' }}
                        } @else {
                        Any
                        }
                    </span>
                    <i class="bi bi-chevron-down small"></i>
                </button>
                <div class="dropdown-menu shadow border-0 mt-2 rounded-4 overflow-hidden p-3" style="min-width: 250px;"
                    [class.show]="isPriceDropdownOpen()">
                    <div class="mb-3">
                        <label class="form-label small fw-bold text-muted">Price Range</label>
                        <div class="d-flex gap-2 align-items-center">
                            <input type="number" class="form-control form-control-sm" placeholder="Min"
                                [ngModel]="inputMinPrice()" (ngModelChange)="inputMinPrice.set($event)">
                            <span class="text-muted">-</span>
                            <input type="number" class="form-control form-control-sm" placeholder="Max"
                                [ngModel]="inputMaxPrice()" (ngModelChange)="inputMaxPrice.set($event)">
                        </div>
                    </div>
                    <div class="d-flex justify-content-end gap-2">
                        <button class="btn btn-sm btn-light rounded-pill px-3"
                            (click)="updatePriceRange(null, null)">Reset</button>
                        <button class="btn btn-sm btn-primary rounded-pill px-3"
                            (click)="updatePriceRange(inputMinPrice(), inputMaxPrice())">Apply</button>
                    </div>
                </div>
            </div>

            <div class="dropdown">
                <button
                    class="btn btn-outline-primary rounded-pill px-3 d-flex align-items-center gap-2 border-0 bg-white shadow-sm"
                    type="button" (click)="toggleSortDropdown()">
                    <span class="small text-muted text-uppercase fw-bold">Sort By:</span>
                    <span class="fw-bold text-dark">
                        @switch (sortOption()) {
                        @case ('recommended') { Recommended }
                        @case ('popularity') { Popularity }
                        @case ('price-asc') { Price: Low to High }
                        @case ('price-desc') { Price: High to Low }
                        @case ('rating') { Top Rated }
                        }
                    </span>
                    <i class="bi bi-chevron-down small"></i>
                </button>
                <ul class="dropdown-menu dropdown-menu-end shadow border-0 mt-2 rounded-4 overflow-hidden p-0"
                    [class.show]="isSortDropdownOpen()">
                    <li><button class="dropdown-item py-2 px-3 small fw-medium"
                            (click)="updateSort('recommended')">Recommended</button></li>
                    <li><button class="dropdown-item py-2 px-3 small fw-medium"
                            (click)="updateSort('popularity')">Popularity</button></li>
                    <li><button class="dropdown-item py-2 px-3 small fw-medium" (click)="updateSort('rating')">Top Rated
                            First</button></li>
                    <li><button class="dropdown-item py-2 px-3 small fw-medium" (click)="updateSort('price-asc')">Price:
                            Low to High</button></li>
                    <li><button class="dropdown-item py-2 px-3 small fw-medium"
                            (click)="updateSort('price-desc')">Price: High to Low</button></li>
                </ul>
            </div>
        </div>
    </div>

    <!-- Destinations Grid -->
    <div class="row g-4">
        @for (destination of filteredDestinations(); track destination.id) {
        <div class="col-lg-4 col-md-6">
            <div class="card h-100 destination-card">
                <div class="position-relative overflow-hidden">
                    <img [src]="destination.imageUrl" [alt]="destination.name" class="card-img-top w-100">
                    <div class="position-absolute top-0 end-0 m-3">
                        <span class="badge bg-white text-dark shadow-sm">{{ destination.price | currency }}</span>
                    </div>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-start mb-2">
                        <h5 class="card-title fw-bold mb-0">{{ destination.name }}</h5>
                        <div class="d-flex align-items-center">
                            <i class="bi bi-star-fill text-warning small me-1"></i>
                            <span class="small fw-bold">{{ destination.rating }}</span>
                        </div>
                    </div>
                    <p class="card-text text-muted small mb-2"><i class="bi bi-geo-alt me-1"></i>{{ destination.location
                        }}</p>
                    <p class="card-text small text-secondary line-clamp-3">{{ destination.description }}</p>
                </div>
                <div class="card-footer bg-white border-0 pt-0 pb-4">
                    <div class="d-flex flex-wrap gap-2 mb-3">
                        <span class="badge bg-light text-secondary fw-normal">{{ destination.type }}</span>
                        @if (destination.popularity === 'High') {
                        <span class="badge bg-danger-subtle text-danger fw-normal">Popular</span>
                        }
                    </div>
                    <button [routerLink]="['/destinations', destination.id]"
                        class="btn btn-primary w-100 rounded-pill">View Details</button>
                </div>
            </div>
        </div>
        } @empty {
        <div class="col-12 text-center py-5">
            <div class="text-muted">
                <i class="bi bi-geo-alt display-1 mb-3 d-block opacity-25"></i>
                <h3>No destinations found</h3>
                <p>Try adjusting your search or filters to find what you're looking for.</p>
                <button class="btn btn-outline-primary rounded-pill mt-3"
                    (click)="updateSearch(''); updateFilter(null); updateMinRating(0)">Clear all filters</button>
            </div>
        </div>
        }
    </div>
</div>

// src/pages/Destinations/Destinations.jsx
import { useState, useMemo } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { getDestinations } from '../../data/destinations.js'
import './Destinations.css'

const allDestinations = getDestinations()

export default function Destinations() {
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedFilter, setSelectedFilter] = useState(null)
  const [sortOption, setSortOption] = useState('recommended')
  const [minRating, setMinRating] = useState(0)
  const [isSortDropdownOpen, setIsSortDropdownOpen] = useState(false)
  const [isPriceDropdownOpen, setIsPriceDropdownOpen] = useState(false)
  const [isRatingDropdownOpen, setIsRatingDropdownOpen] = useState(false)
  const [minPrice, setMinPrice] = useState(null)
  const [maxPrice, setMaxPrice] = useState(null)
  const [inputMinPrice, setInputMinPrice] = useState(null)
  const [inputMaxPrice, setInputMaxPrice] = useState(null)
  const navigate = useNavigate()

  const filteredDestinations = useMemo(() => {
    const query = searchQuery.toLowerCase()
    let result = allDestinations.filter(dest => {
      const matchesSearch = dest.name.toLowerCase().includes(query) ||
        dest.location.toLowerCase().includes(query) ||
        dest.description.toLowerCase().includes(query)
      const matchesFilter = selectedFilter ? dest.type === selectedFilter : true
      const matchesRating = dest.rating >= minRating
      const matchesMinPrice = minPrice === null || dest.price >= minPrice
      const matchesMaxPrice = maxPrice === null || dest.price <= maxPrice
      return matchesSearch && matchesFilter && matchesRating && matchesMinPrice && matchesMaxPrice
    })

    return result.sort((a, b) => {
      switch (sortOption) {
        case 'price-asc': return a.price - b.price
        case 'price-desc': return b.price - a.price
        case 'rating': return b.rating - a.rating
        case 'popularity': {
          const w = { High: 3, Medium: 2, Low: 1 }
          return w[b.popularity] - w[a.popularity]
        }
        default: {
          const s = { High: 10, Medium: 5, Low: 1 }
          return (s[b.popularity] + b.rating * 2) - (s[a.popularity] + a.rating * 2)
        }
      }
    })
  }, [searchQuery, selectedFilter, sortOption, minRating, minPrice, maxPrice])

  const sortLabel = {
    recommended: 'Recommended',
    popularity: 'Popularity',
    'price-asc': 'Price: Low to High',
    'price-desc': 'Price: High to Low',
    rating: 'Top Rated'
  }[sortOption]

  const ratingLabel = {
    0: 'All Ratings',
    4: '4.0+ ★',
    4.5: '4.5+ ★',
    4.8: '4.8+ ★'
  }[minRating]

  const handleSort = (sort) => {
    setSortOption(sort)
    setIsSortDropdownOpen(false)
  }

  const handleApplyPrice = () => {
    setMinPrice(inputMinPrice)
    setMaxPrice(inputMaxPrice)
    setIsPriceDropdownOpen(false)
  }

  const clearAllFilters = () => {
    setSearchQuery('')
    setSelectedFilter(null)
    setMinRating(0)
    setMinPrice(null)
    setMaxPrice(null)
    setIsRatingDropdownOpen(false)
    setIsPriceDropdownOpen(false)
    setIsSortDropdownOpen(false)
  }

  return (
    <div className="container py-5 mt-5">
      <div className="text-center mb-5 pt-4">
        <h1>Explore Destinations</h1>
        <p className="text-muted">Discover the world's most breathtaking places.</p>
      </div>

      {/* Centered Search Bar Container */}
      <div className="search-bar-container mb-4">
        <div className="search-wrapper">
          <i className="bi bi-search search-icon"></i>
          <input
            type="text"
            className="search-input"
            placeholder="Search destinations by name, location or details..."
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
          />
          {searchQuery && (
            <button className="clear-search-btn" onClick={() => setSearchQuery('')} aria-label="Clear search">
              <i className="bi bi-x-lg"></i>
            </button>
          )}
        </div>
      </div>

      {/* Category Tabs (Minimal Text Links with Gold underline) */}
      <div className="category-tabs-container mb-4">
        {['All', 'Beach', 'City', 'Cultural', 'Nature', 'Mountain'].map(f => (
          <button
            key={f}
            className={`category-tab ${(f === 'All' && !selectedFilter) || selectedFilter === f ? 'active' : ''}`}
            onClick={() => setSelectedFilter(f === 'All' ? null : f)}
          >
            {f}
          </button>
        ))}
      </div>

      {/* Refine Controls Bar (Rating, Price, Sort dropdowns) */}
      <div className="refine-bar mb-5">
        <span className="refine-label">Refine by:</span>
        <div className="refine-controls">
          {/* Rating Dropdown */}
          <div className="dropdown position-relative">
            <button
              className={`filter-pill dropdown-trigger ${minRating > 0 ? 'active' : ''}`}
              onClick={() => {
                setIsRatingDropdownOpen(v => !v)
                setIsPriceDropdownOpen(false)
                setIsSortDropdownOpen(false)
              }}
            >
              <i className="bi bi-star me-1"></i>
              {ratingLabel}
              <i className="bi bi-chevron-down ms-1 small"></i>
            </button>
            {isRatingDropdownOpen && (
              <ul className="dropdown-menu show shadow border-0 mt-2 rounded-4 overflow-hidden p-0" style={{ minWidth: '150px', right: 0, left: 'auto', zIndex: 100 }}>
                {[0, 4, 4.5, 4.8].map(r => (
                  <li key={r}>
                    <button
                      className={`dropdown-item py-2 px-3 small fw-medium ${minRating === r ? 'active-item' : ''}`}
                      onClick={() => {
                        setMinRating(r)
                        setIsRatingDropdownOpen(false)
                      }}
                    >
                      {r === 0 ? 'All Ratings' : `${r}+ ★`}
                    </button>
                  </li>
                ))}
              </ul>
            )}
          </div>

          {/* Price Dropdown */}
          <div className="dropdown position-relative">
            <button
              className={`filter-pill dropdown-trigger ${minPrice !== null || maxPrice !== null ? 'active' : ''}`}
              onClick={() => {
                if (!isPriceDropdownOpen) {
                  setInputMinPrice(minPrice)
                  setInputMaxPrice(maxPrice)
                }
                setIsPriceDropdownOpen(v => !v)
                setIsSortDropdownOpen(false)
                setIsRatingDropdownOpen(false)
              }}
            >
              <i className="bi bi-sliders me-1"></i>
              Price {minPrice !== null || maxPrice !== null ? `($${minPrice ?? 0}-${maxPrice ?? 'Any'})` : ''}
              <i className="bi bi-chevron-down ms-1 small"></i>
            </button>
            {isPriceDropdownOpen && (
              <div className="dropdown-menu show shadow border-0 mt-2 rounded-4 p-3" style={{ minWidth: '240px', right: 0, left: 'auto', zIndex: 100 }}>
                <div className="mb-2">
                  <label className="form-label small fw-bold">Min Price ($)</label>
                  <input type="number" className="form-control form-control-sm" placeholder="0"
                    value={inputMinPrice ?? ''} onChange={e => setInputMinPrice(e.target.value ? Number(e.target.value) : null)} />
                </div>
                <div className="mb-3">
                  <label className="form-label small fw-bold">Max Price ($)</label>
                  <input type="number" className="form-control form-control-sm" placeholder="Any"
                    value={inputMaxPrice ?? ''} onChange={e => setInputMaxPrice(e.target.value ? Number(e.target.value) : null)} />
                </div>
                <div className="d-flex gap-2">
                  <button className="btn btn-primary btn-sm rounded-pill flex-fill" onClick={handleApplyPrice}>Apply</button>
                  <button className="btn btn-outline-secondary btn-sm rounded-pill" onClick={() => { setMinPrice(null); setMaxPrice(null); setIsPriceDropdownOpen(false) }}>Clear</button>
                </div>
              </div>
            )}
          </div>

          {/* Sort Dropdown */}
          <div className="dropdown position-relative">
            <button
              className="filter-pill dropdown-trigger"
              onClick={() => {
                setIsSortDropdownOpen(v => !v)
                setIsPriceDropdownOpen(false)
                setIsRatingDropdownOpen(false)
              }}
            >
              <i className="bi bi-sort-down me-1"></i>
              {sortLabel}
              <i className="bi bi-chevron-down ms-1 small"></i>
            </button>
            {isSortDropdownOpen && (
              <ul className="dropdown-menu show shadow border-0 mt-2 rounded-4 overflow-hidden p-0" style={{ minWidth: '180px', right: 0, left: 'auto', zIndex: 100 }}>
                {[['recommended', 'Recommended'], ['popularity', 'Popularity'], ['rating', 'Top Rated First'], ['price-asc', 'Price: Low to High'], ['price-desc', 'Price: High to Low']].map(([val, label]) => (
                  <li key={val}>
                    <button className="dropdown-item py-2 px-3 small fw-medium" onClick={() => handleSort(val)}>{label}</button>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>
      </div>

      {/* Destinations Grid */}
      <div className="row g-4">
        {filteredDestinations.length > 0 ? filteredDestinations.map(dest => (
          <div key={dest.id} className="col-lg-4 col-md-6">
            <div className="card h-100 destination-card">
              <div className="position-relative overflow-hidden">
                <img src={dest.imageUrl} alt={dest.name} className="card-img-top w-100" />
                <div className="position-absolute top-0 end-0 m-3">
                  <span className="badge bg-white text-dark shadow-sm">${dest.price.toLocaleString()}</span>
                </div>
              </div>
              <div className="card-body">
                <div className="d-flex justify-content-between align-items-start mb-2">
                  <h5 className="card-title fw-bold mb-0">{dest.name}</h5>
                  <div className="d-flex align-items-center">
                    <i className="bi bi-star-fill text-warning small me-1"></i>
                    <span className="small fw-bold">{dest.rating}</span>
                  </div>
                </div>
                <p className="card-text text-muted small mb-2"><i className="bi bi-geo-alt me-1"></i>{dest.location}</p>
                <p className="card-text small text-secondary line-clamp-3">{dest.description}</p>
              </div>
              <div className="card-footer bg-white border-0 pt-0 pb-4">
                <div className="d-flex flex-wrap gap-2 mb-3">
                  <span className="badge bg-light text-secondary fw-normal">{dest.type}</span>
                  {dest.popularity === 'High' && <span className="badge bg-danger-subtle text-danger fw-normal">Popular</span>}
                </div>
                <button onClick={() => navigate(`/destinations/${dest.id}`)} className="btn btn-primary w-100 rounded-pill">
                  View Details
                </button>
              </div>
            </div>
          </div>
        )) : (
          <div className="col-12 text-center py-5">
            <div className="text-muted">
              <i className="bi bi-geo-alt display-1 mb-3 d-block opacity-25"></i>
              <h3>No destinations found</h3>
              <p>Try adjusting your search or filters to find what you're looking for.</p>
              <button className="btn btn-outline-primary rounded-pill mt-3" onClick={clearAllFilters}>
                Clear all filters
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
