// src/pages/Contact/Contact.jsx
import { useState } from 'react'
import './Contact.css'

export default function Contact() {
  const [form, setForm] = useState({ name: '', email: '', subject: '', message: '' })
  const [submitted, setSubmitted] = useState(false)
  const [isLoading, setIsLoading] = useState(false)

  const handleChange = (e) => setForm(prev => ({ ...prev, [e.target.name]: e.target.value }))

  const handleSubmit = (e) => {
    e.preventDefault()
    setIsLoading(true)
    setTimeout(() => {
      setIsLoading(false)
      setSubmitted(true)
    }, 1000)
  }

  return (
    <div className="contact-page">
      <div className="container">
        {/* Hero */}
        <div className="contact-hero text-center">
          <h1>Contact Us</h1>
          <p className="lead">We'd love to hear from you. Let us know how we can help.</p>
        </div>

        <div className="row g-5">
          {/* Info Column */}
          <div className="col-lg-4">
            <div className="contact-info-card">
              <h2 className="section-title">Get In Touch</h2>
              <p className="text-muted mb-4">Whether you have a question about our tours, pricing, or anything else, our team is ready to answer all your questions.</p>

              {[
                { icon: 'bi-geo-alt-fill', title: 'Visit Us', desc: '123 Luxury Lane, Travel City, TC 12345' },
                { icon: 'bi-telephone-fill', title: 'Call Us', desc: '+1 (555) 123-4567' },
                { icon: 'bi-envelope-fill', title: 'Email Us', desc: 'hello@eleve.travel' },
                { icon: 'bi-clock-fill', title: 'Working Hours', desc: 'Mon-Fri: 9AM – 6PM' }
              ].map(item => (
                <div key={item.title} className="info-item d-flex gap-3 mb-4">
                  <div className="icon-box">
                    <i className={`bi ${item.icon}`}></i>
                  </div>
                  <div>
                    <h5>{item.title}</h5>
                    <p className="text-muted mb-0">{item.desc}</p>
                  </div>
                </div>
              ))}

              <h5 className="mt-4 mb-3">Follow Us</h5>
              <div className="social-links">
                {[
                  { icon: 'bi-instagram', href: 'https://instagram.com', label: 'Instagram' },
                  { icon: 'bi-twitter-x', href: 'https://twitter.com', label: 'Twitter' },
                  { icon: 'bi-facebook', href: 'https://facebook.com', label: 'Facebook' }
                ].map(s => (
                  <a key={s.icon} href={s.href} target="_blank" rel="noopener noreferrer" aria-label={s.label}>
                    <i className={`bi ${s.icon}`}></i>
                  </a>
                ))}
              </div>
            </div>
          </div>

          {/* Form Column */}
          <div className="col-lg-8">
            <div className="contact-form-card">
              {submitted ? (
                <div className="alert-success text-center p-5 rounded-4">
                  <i className="bi bi-check-circle-fill text-success display-4 mb-3 d-block"></i>
                  <h3 className="fw-bold">Message Sent!</h3>
                  <p className="text-muted">Thank you for reaching out. We'll get back to you within 24 hours.</p>
                </div>
              ) : (
                <form onSubmit={handleSubmit} noValidate>
                  <div className="row g-3 mb-3">
                    <div className="col-md-6">
                      <div className="form-group">
                        <label>Full Name</label>
                        <input type="text" name="name" value={form.name} onChange={handleChange}
                          placeholder="John Doe" required />
                      </div>
                    </div>
                    <div className="col-md-6">
                      <div className="form-group">
                        <label>Email Address</label>
                        <input type="email" name="email" value={form.email} onChange={handleChange}
                          placeholder="john@example.com" required />
                      </div>
                    </div>
                  </div>

                  <div className="form-group mb-3">
                    <label>Subject</label>
                    <input type="text" name="subject" value={form.subject} onChange={handleChange}
                      placeholder="How can we help?" required />
                  </div>

                  <div className="form-group mb-4">
                    <label>Message</label>
                    <textarea name="message" rows="6" value={form.message} onChange={handleChange}
                      placeholder="Tell us more about your inquiry..."></textarea>
                  </div>

                  <button type="submit" className="btn-submit" disabled={isLoading}>
                    {isLoading ? 'Sending...' : 'Send Message'}
                  </button>
                </form>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// src/app/pages/contact/contact.component.ts
import { Component, ChangeDetectionStrategy, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
    selector: 'app-contact',
    standalone: true,
    imports: [CommonModule, FormsModule],
    templateUrl: './contact.component.html',
    styleUrls: ['./contact.component.css'],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class ContactComponent {
    name = signal('');
    email = signal('');
    subject = signal('');
    message = signal('');

    isSubmitting = signal(false);
    successMessage = signal('');

    onSubmit() {
        this.isSubmitting.set(true);

        // Simulate network request
        setTimeout(() => {
            this.isSubmitting.set(false);
            this.successMessage.set('Thank you for contacting us! We will get back to you shortly.');

            // Reset form
            this.name.set('');
            this.email.set('');
            this.subject.set('');
            this.message.set('');

            // Clear success message after 5 seconds
            setTimeout(() => this.successMessage.set(''), 5000);
        }, 1000);
    }
}

<div class="contact-page">
    <!-- Hero Section -->
    <section class="contact-hero d-flex align-items-center justify-content-center text-center">
        <div class="container position-relative z-2">
            <h1>Get in Touch</h1>
            <p class="lead">We'd love to hear from you. Let's start a conversation.</p>
        </div>
    </section>

    <div class="container content-wrapper">
        <div class="row g-5">
            <!-- Left: Contact Details -->
            <div class="col-lg-5">
                <div class="contact-info-card">
                    <h3 class="section-title">Contact Information</h3>
                    <p class="text-muted mb-5">Have a question or just want to say hi? We'd love to hear from you.</p>

                    <div class="info-item d-flex align-items-start gap-3 mb-4">
                        <div class="icon-box">
                            <i class="bi bi-geo-alt"></i>
                        </div>
                        <div>
                            <h5>Our Location</h5>
                            <p class="text-muted">123 Luxury Avenue, Suite 100<br>New York, NY 10001</p>
                        </div>
                    </div>

                    <div class="info-item d-flex align-items-start gap-3 mb-4">
                        <div class="icon-box">
                            <i class="bi bi-envelope"></i>
                        </div>
                        <div>
                            <h5>Email Us</h5>
                            <p class="text-muted">concierge@luxurytravel.com</p>
                        </div>
                    </div>

                    <div class="info-item d-flex align-items-start gap-3 mb-4">
                        <div class="icon-box">
                            <i class="bi bi-telephone"></i>
                        </div>
                        <div>
                            <h5>Call Us</h5>
                            <p class="text-muted">+1 (555) 123-4567</p>
                        </div>
                    </div>

                    <div class="social-links mt-5">
                        <a href="#"><i class="bi bi-instagram"></i></a>
                        <a href="#"><i class="bi bi-twitter-x"></i></a>
                        <a href="#"><i class="bi bi-facebook"></i></a>
                        <a href="#"><i class="bi bi-linkedin"></i></a>
                    </div>
                </div>
            </div>

            <!-- Right: Contact Form -->
            <div class="col-lg-7">
                <div class="contact-form-card">
                    <h3 class="section-title mb-4">Send us a Message</h3>

                    @if (successMessage()) {
                    <div class="alert alert-success d-flex align-items-center gap-2 mb-4">
                        <i class="bi bi-check-circle-fill"></i>
                        <div>{{ successMessage() }}</div>
                    </div>
                    }

                    <form (submit)="onSubmit(); $event.preventDefault()">
                        <div class="row g-4">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="name">Your Name</label>
                                    <input type="text" id="name" name="name" [ngModel]="name()"
                                        (ngModelChange)="name.set($event)" placeholder="John Doe" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="email">Your Email</label>
                                    <input type="email" id="email" name="email" [ngModel]="email()"
                                        (ngModelChange)="email.set($event)" placeholder="john@example.com" required>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <label for="subject">Subject</label>
                                    <input type="text" id="subject" name="subject" [ngModel]="subject()"
                                        (ngModelChange)="subject.set($event)" placeholder="How can we help?" required>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <label for="message">Message</label>
                                    <textarea id="message" name="message" rows="5" [ngModel]="message()"
                                        (ngModelChange)="message.set($event)"
                                        placeholder="Tell us about your travel plans..." required></textarea>
                                </div>
                            </div>
                            <div class="col-12">
                                <button type="submit" class="btn-submit" [disabled]="isSubmitting()">
                                    @if (isSubmitting()) {
                                    <span class="spinner-border spinner-border-sm me-2"></span> Sending...
                                    } @else {
                                    Send Message
                                    }
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
