// src/app/components/hero/hero.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  signal,
  computed,
  Inject,
  PLATFORM_ID,
  ElementRef,
  AfterViewInit,
  OnDestroy,
  NgZone,
  viewChild
} from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Destination } from '../../pages/destinations/destination.model';

@Component({
  selector: 'app-hero',
  imports: [CommonModule, RouterLink],
  templateUrl: './hero.component.html',
  styleUrl: './hero.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class HeroComponent implements AfterViewInit, OnDestroy {
  readonly canvasRef = viewChild<ElementRef<HTMLCanvasElement>>('heroCanvas');

  /** 0 = top, 1 = animation complete */
  scrollProgress = signal(0);

  /**
   * Derived text animation values — Jesko Jets style:
   * Text falls DOWN, scales UP, fades OUT on scroll.
   * Each element has slightly different timing for stagger.
   */

  // Center title: fades out fastest (by 15% scroll)
  titleOpacity = computed(() => Math.max(0, 1 - this.scrollProgress() * 7));
  titleScale = computed(() => 1 + this.scrollProgress() * 3);
  titleTranslateY = computed(() => this.scrollProgress() * 120);

  // Left heading: fades out by ~25% scroll
  leftOpacity = computed(() => Math.max(0, 1 - this.scrollProgress() * 4));
  leftScale = computed(() => 1 + this.scrollProgress() * 1.5);
  leftTranslateY = computed(() => this.scrollProgress() * 200);

  // Right heading: slightly delayed, fades by ~30%
  rightOpacity = computed(() => Math.max(0, 1 - this.scrollProgress() * 3.5));
  rightScale = computed(() => 1 + this.scrollProgress() * 1.2);
  rightTranslateY = computed(() => this.scrollProgress() * 180);

  // Bottom left text: fades by ~20%
  bottomLeftOpacity = computed(() => Math.max(0, 1 - this.scrollProgress() * 5));
  bottomLeftTranslateY = computed(() => this.scrollProgress() * 150);

  // Bottom right (scroll hint): fades by ~15%
  bottomRightOpacity = computed(() => Math.max(0, 1 - this.scrollProgress() * 6));

  // CTA button: fades out by ~12% scroll
  ctaOpacity = computed(() => Math.max(0, 1 - this.scrollProgress() * 8));
  ctaTranslateY = computed(() => this.scrollProgress() * 100);

  // Destinations list - we could ideally inject the DestinationsService but keeping it static here for animation sync
  readonly destinations: Pick<Destination, 'id' | 'name'>[] = [
    { id: 1, name: 'Bali' },
    { id: 2, name: 'Paris' },
    { id: 3, name: 'Kyoto' },
    { id: 4, name: 'Santorini' },
    { id: 5, name: 'Machu Picchu' },
    { id: 6, name: 'Grand Canyon' },
    { id: 7, name: 'Swiss Alps' },
    { id: 8, name: 'Dubai' },
    { id: 9, name: 'Rome' },
    { id: 10, name: 'New York' },
    { id: 11, name: 'Cairo' }
  ];

  // Duplicate the array many times so items keep scrolling until the very last frame
  readonly loopedDestinations = [
    ...this.destinations,
    ...this.destinations,
    ...this.destinations,
    ...this.destinations,
    ...this.destinations,
    ...this.destinations,
    ...this.destinations,
    ...this.destinations
  ];

  /**
   * Destination list: items appear during the tower phase (scroll 30% onwards).
   * A vertical list on the right side that moves up and fades at boundaries.
   * Stays visible until the very last scroll frame.
   */
  destContainerOpacity = computed(() => {
    const p = this.scrollProgress();
    // Start appearing after the clouds finish passing (around 30% scroll mark)
    if (p < 0.30) return 0;
    // Stay fully visible until the end — no early fade-out
    return Math.min(1, (p - 0.30) * 8);
  });

  // Vertical movement offset driven by scroll
  destTranslateY = computed(() => {
    const p = this.scrollProgress();
    // Map tower phase (0.30 to 1.00) to a progress from 0 to 1
    const phaseProgress = Math.min(1, Math.max(0, (p - 0.30) / 0.70));

    // With 8x duplicated array (88 items total), each ~80px high with gap.
    // Slow down the travel so items are still visible at the very last frame.
    return 300 - (phaseProgress * 6000);
  });

  /**
   * Discover More Button opacity: Fades in at the tower phase
   */
  discoverBtnOpacity = computed(() => {
    const p = this.scrollProgress();
    // Fade in between 65% and 80% scroll progress (later in the tower phase)
    if (p < 0.65) return 0;
    return Math.min(1, (p - 0.65) * 6);
  });

  private context: CanvasRenderingContext2D | null = null;
  private images: HTMLImageElement[] = [];
  private readonly totalFrames = 192;
  private displayedFrame = 1;
  private targetFrame = 1;
  private animationId: number | null = null;
  private resizeTimeout: ReturnType<typeof setTimeout> | undefined;
  private scrollHandler: (() => void) | null = null;
  private resizeHandler: (() => void) | null = null;

  constructor(
    @Inject(PLATFORM_ID) private platformId: Object,
    private ngZone: NgZone
  ) { }

  ngAfterViewInit() {
    if (isPlatformBrowser(this.platformId)) {
      this.initCanvas();
      this.preloadImages();
      this.setupScrollListener();
      this.startRenderLoop();
    }
  }

  ngOnDestroy() {
    if (this.scrollHandler) {
      window.removeEventListener('scroll', this.scrollHandler);
    }
    if (this.resizeHandler) {
      window.removeEventListener('resize', this.resizeHandler);
    }
    if (this.animationId !== null) {
      cancelAnimationFrame(this.animationId);
    }
  }

  private initCanvas() {
    const canvasEl = this.canvasRef();
    if (!canvasEl) return;
    this.context = canvasEl.nativeElement.getContext('2d');
    this.resizeCanvas();

    this.resizeHandler = () => {
      clearTimeout(this.resizeTimeout);
      this.resizeTimeout = setTimeout(() => {
        this.resizeCanvas();
        this.drawFrame(this.displayedFrame);
      }, 100);
    };

    this.ngZone.runOutsideAngular(() => {
      window.addEventListener('resize', this.resizeHandler!);
    });
  }

  private resizeCanvas() {
    const canvasEl = this.canvasRef();
    if (!canvasEl) return;
    const canvas = canvasEl.nativeElement;
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
  }

  private preloadImages() {
    for (let i = 1; i <= this.totalFrames; i++) {
      const img = new Image();
      img.src = `home_animation_pics/${i.toString().padStart(5, '0')}.png`;
      if (i === 1) {
        img.onload = () => this.drawFrame(1);
      }
      this.images.push(img);
    }
  }

  private drawFrame(frameIndex: number) {
    if (!this.context) return;
    const canvasEl = this.canvasRef();
    if (!canvasEl) return;
    const canvas = canvasEl.nativeElement;
    const image = this.images[frameIndex - 1];

    if (image?.complete && image.naturalWidth !== 0) {
      const ratio = Math.max(canvas.width / image.width, canvas.height / image.height);
      const cx = (canvas.width - image.width * ratio) / 2;
      const cy = (canvas.height - image.height * ratio) / 2;

      this.context.clearRect(0, 0, canvas.width, canvas.height);
      this.context.drawImage(image, 0, 0, image.width, image.height,
        cx, cy, image.width * ratio, image.height * ratio);
    }
  }

  /**
   * Smooth render loop: advances toward target at adaptive speed.
   * Small gap = 1 frame/tick (smooth). Large gap = up to 4 frames/tick
   * (keeps up with fast scrolling, no stalling at clouds).
   */
  private startRenderLoop() {
    this.ngZone.runOutsideAngular(() => {
      const tick = () => {
        const gap = this.targetFrame - this.displayedFrame;
        if (gap !== 0) {
          // Adaptive step: advance faster when further behind
          const absGap = Math.abs(gap);
          const step = absGap > 20 ? 4 : absGap > 8 ? 3 : absGap > 3 ? 2 : 1;
          const direction = gap > 0 ? 1 : -1;

          this.displayedFrame += direction * Math.min(step, absGap);
          this.drawFrame(this.displayedFrame);
        }
        this.animationId = requestAnimationFrame(tick);
      };
      this.animationId = requestAnimationFrame(tick);
    });
  }

  /** Scroll listener: sets the TARGET frame + text animation progress */
  private setupScrollListener() {
    this.scrollHandler = () => {
      const scrollY = window.scrollY;
      const heroContainer = document.querySelector('.hero-scroll-container') as HTMLElement;
      if (!heroContainer) return;

      const scrollableDist = heroContainer.scrollHeight - window.innerHeight;
      if (scrollableDist <= 0) return;

      const fraction = Math.min(1, Math.max(0, scrollY / scrollableDist));

      // Update text animation progress
      this.ngZone.run(() => this.scrollProgress.set(fraction));

      // Set target frame (the render loop will smoothly catch up)
      this.targetFrame = Math.min(this.totalFrames,
        Math.max(1, Math.floor(fraction * this.totalFrames) + 1));
    };

    this.ngZone.runOutsideAngular(() => {
      window.addEventListener('scroll', this.scrollHandler!, { passive: true });
    });
  }
}

<section class="hero-scroll-container">
    <div class="sticky-canvas-container">
        <canvas #heroCanvas></canvas>

        <!-- Black vignette overlays on both sides -->
        <div class="vignette-left" [style.opacity]="destContainerOpacity()"></div>
        <div class="vignette-right" [style.opacity]="destContainerOpacity()"></div>

        <!-- VERTICAL DESTINATIONS — stays sticky with canvas, visible during tower phase -->
        <div class="dest-list-container" [style.opacity]="destContainerOpacity()"
            [style.visibility]="destContainerOpacity() === 0 ? 'hidden' : 'visible'">
            <div class="dest-list" [style.transform]="'translateY(' + destTranslateY() + 'px)'">
                @for (dest of loopedDestinations; track $index) {
                <div class="dest-list-item">
                    <span class="dest-list-label">{{ dest.name }}</span>
                    <a [routerLink]="['/destinations', dest.id]" class="dest-explore-btn">Explore</a>
                </div>
                }
            </div>
        </div>

        <!-- Discover More — bold text beside the tower, fades in during tower phase -->
        <div class="discover-more-container" [style.opacity]="discoverBtnOpacity()"
            [style.visibility]="discoverBtnOpacity() === 0 ? 'hidden' : 'visible'">
            <a routerLink="/destinations" class="discover-more-link">Discover<br><em>more</em></a>
        </div>
    </div>

    <!-- Text overlay — all elements use scroll-driven fall/zoom/fade -->
    <div class="scroll-content">
        <div class="hero-viewport">

            <!-- CENTER: "ELEVÉ" title over the window -->
            <div class="hero-center-title" [style.opacity]="titleOpacity()"
                [style.transform]="'translate(-50%, -50%) scale(' + titleScale() + ') translateY(' + titleTranslateY() + 'px)'">
                <span class="center-title-text">ELEVÉ</span>
            </div>

            <!-- LEFT: Main heading -->
            <div class="hero-text-left" [style.opacity]="leftOpacity()"
                [style.transform]="'scale(' + leftScale() + ') translateY(' + leftTranslateY() + 'px)'">
                <h1 class="hero-large-text">We are<br><em>exploration</em></h1>
            </div>

            <!-- RIGHT: Secondary heading -->
            <div class="hero-text-right" [style.opacity]="rightOpacity()"
                [style.transform]="'scale(' + rightScale() + ') translateY(' + rightTranslateY() + 'px)'">
                <h1 class="hero-large-text">We are<br><em>distinction</em></h1>
            </div>

            <!-- BOTTOM LEFT: Tagline & description -->
            <div class="hero-text-bottom-left" [style.opacity]="bottomLeftOpacity()"
                [style.transform]="'translateY(' + bottomLeftTranslateY() + 'px)'">
                <h3 class="hero-tagline">Your freedom to<br>explore the cosmos</h3>
                <p class="hero-desc">
                    Every journey is designed around your comfort, time, and ambitions — so you can focus on what truly
                    matters, while we take care of everything&nbsp;else.
                </p>
            </div>

            <!-- BOTTOM RIGHT: Scroll hint -->
            <div class="hero-text-bottom-right" [style.opacity]="bottomRightOpacity()">
                <div class="scroll-cue">
                    <span class="scroll-cue-arrow">↓</span>
                    <span class="scroll-cue-label">SCROLL DOWN</span>
                    <span class="scroll-cue-sub">TO START THE JOURNEY</span>
                </div>
            </div>

            <!-- BOTTOM CENTER: CTA Button -->
            <div class="hero-cta-center" [style.opacity]="ctaOpacity()"
                [style.transform]="'translateX(-50%) translateY(' + ctaTranslateY() + 'px)'">
                <a routerLink="/book-tour" class="cta-btn">
                    <span class="cta-label">Book a Tour</span>
                    <span class="cta-icon-circle">
                        <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="white" viewBox="0 0 16 16">
                            <path
                                d="M6.428 1.151C6.708.591 7.213 0 8 0s1.292.592 1.572 1.151C9.861 1.73 10 2.431 10 3v3.691l5.17 2.585a1.5 1.5 0 0 1 .83 1.342V12a.5.5 0 0 1-.582.493l-5.507-.918-.375 2.253 1.318 1.318A.5.5 0 0 1 10.5 16h-5a.5.5 0 0 1-.354-.854l1.319-1.318-.376-2.253-5.507.918A.5.5 0 0 1 0 12v-1.382a1.5 1.5 0 0 1 .83-1.342L6 6.691V3c0-.568.14-1.271.428-1.849Z" />
                        </svg>
                    </span>
                </a>
            </div>

        </div>

        <!-- Subsequent viewports (pure scroll space — canvas keeps animating) -->
        <div class="hero-viewport"></div>
        <div class="hero-viewport"></div>
    </div>
</section>

// src/components/Hero/Hero.jsx
import { useRef, useEffect, useState, useCallback } from 'react'
import { Link } from 'react-router-dom'
import './Hero.css'

const TOTAL_FRAMES = 192

const destinations = [
  { id: 1, name: 'Bali' },
  { id: 2, name: 'Paris' },
  { id: 3, name: 'Kyoto' },
  { id: 4, name: 'Santorini' },
  { id: 5, name: 'Machu Picchu' },
  { id: 6, name: 'Grand Canyon' },
  { id: 7, name: 'Swiss Alps' },
  { id: 8, name: 'Dubai' },
  { id: 9, name: 'Rome' },
  { id: 10, name: 'New York' },
  { id: 11, name: 'Cairo' }
]

// Duplicate 8x for looped scroll
const loopedDestinations = [
  ...destinations, ...destinations, ...destinations, ...destinations,
  ...destinations, ...destinations, ...destinations, ...destinations
]

function clamp(val, min, max) {
  return Math.max(min, Math.min(max, val))
}

export default function Hero() {
  const canvasRef = useRef(null)
  const imagesRef = useRef([])
  const displayedFrameRef = useRef(1)
  const targetFrameRef = useRef(1)
  const animationIdRef = useRef(null)
  const resizeTimeoutRef = useRef(null)
  const contextRef = useRef(null)

  const [scrollProgress, setScrollProgress] = useState(0)

  // Derived animation values
  const p = scrollProgress

  // Center title
  const titleOpacity = clamp(1 - p * 7, 0, 1)
  const titleScale = 1 + p * 3
  const titleTranslateY = p * 120

  // Left heading
  const leftOpacity = clamp(1 - p * 4, 0, 1)
  const leftScale = 1 + p * 1.5
  const leftTranslateY = p * 200

  // Right heading
  const rightOpacity = clamp(1 - p * 3.5, 0, 1)
  const rightScale = 1 + p * 1.2
  const rightTranslateY = p * 180

  // Bottom left
  const bottomLeftOpacity = clamp(1 - p * 5, 0, 1)
  const bottomLeftTranslateY = p * 150

  // Bottom right
  const bottomRightOpacity = clamp(1 - p * 6, 0, 1)

  // CTA
  const ctaOpacity = clamp(1 - p * 8, 0, 1)
  const ctaTranslateY = p * 100

  // Destinations list
  const destContainerOpacity = p < 0.30 ? 0 : clamp((p - 0.30) * 8, 0, 1)
  const phaseProgress = clamp((p - 0.30) / 0.70, 0, 1)
  const destTranslateY = 300 - (phaseProgress * 6000)

  // Discover button
  const discoverBtnOpacity = p < 0.65 ? 0 : clamp((p - 0.65) * 6, 0, 1)

  const drawFrame = useCallback((frameIndex) => {
    const ctx = contextRef.current
    const canvas = canvasRef.current
    if (!ctx || !canvas) return
    const image = imagesRef.current[frameIndex - 1]
    if (image?.complete && image.naturalWidth !== 0) {
      const ratio = Math.max(canvas.width / image.width, canvas.height / image.height)
      const cx = (canvas.width - image.width * ratio) / 2
      const cy = (canvas.height - image.height * ratio) / 2
      ctx.clearRect(0, 0, canvas.width, canvas.height)
      ctx.drawImage(image, 0, 0, image.width, image.height,
        cx, cy, image.width * ratio, image.height * ratio)
    }
  }, [])

  const resizeCanvas = useCallback(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    canvas.width = window.innerWidth
    canvas.height = window.innerHeight
  }, [])

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    contextRef.current = canvas.getContext('2d')
    resizeCanvas()

    // Preload images
    for (let i = 1; i <= TOTAL_FRAMES; i++) {
      const img = new Image()
      img.src = `/home_animation_pics/${String(i).padStart(5, '0')}.png`
      if (i === 1) {
        img.onload = () => drawFrame(1)
      }
      imagesRef.current.push(img)
    }

    // Render loop
    const tick = () => {
      const gap = targetFrameRef.current - displayedFrameRef.current
      if (gap !== 0) {
        const absGap = Math.abs(gap)
        const step = absGap > 20 ? 4 : absGap > 8 ? 3 : absGap > 3 ? 2 : 1
        const direction = gap > 0 ? 1 : -1
        displayedFrameRef.current += direction * Math.min(step, absGap)
        drawFrame(displayedFrameRef.current)
      }
      animationIdRef.current = requestAnimationFrame(tick)
    }
    animationIdRef.current = requestAnimationFrame(tick)

    // Scroll listener
    const handleScroll = () => {
      const heroContainer = document.querySelector('.hero-scroll-container')
      if (!heroContainer) return
      const scrollableDist = heroContainer.scrollHeight - window.innerHeight
      if (scrollableDist <= 0) return
      const fraction = clamp(window.scrollY / scrollableDist, 0, 1)
      setScrollProgress(fraction)
      targetFrameRef.current = clamp(Math.floor(fraction * TOTAL_FRAMES) + 1, 1, TOTAL_FRAMES)
    }

    // Resize listener
    const handleResize = () => {
      clearTimeout(resizeTimeoutRef.current)
      resizeTimeoutRef.current = setTimeout(() => {
        resizeCanvas()
        drawFrame(displayedFrameRef.current)
      }, 100)
    }

    window.addEventListener('scroll', handleScroll, { passive: true })
    window.addEventListener('resize', handleResize)

    return () => {
      window.removeEventListener('scroll', handleScroll)
      window.removeEventListener('resize', handleResize)
      if (animationIdRef.current) cancelAnimationFrame(animationIdRef.current)
      clearTimeout(resizeTimeoutRef.current)
    }
  }, [drawFrame, resizeCanvas])

  return (
    <section className="hero-scroll-container">
      <div className="sticky-canvas-container">
        <canvas ref={canvasRef}></canvas>

        {/* Black vignette overlays */}
        <div className="vignette-left" style={{ opacity: destContainerOpacity }}></div>
        <div className="vignette-right" style={{ opacity: destContainerOpacity }}></div>

        {/* Vertical Destinations list */}
        <div
          className="dest-list-container"
          style={{
            opacity: destContainerOpacity,
            visibility: destContainerOpacity === 0 ? 'hidden' : 'visible'
          }}
        >
          <div className="dest-list" style={{ transform: `translateY(${destTranslateY}px)` }}>
            {loopedDestinations.map((dest, idx) => (
              <div key={idx} className="dest-list-item">
                <span className="dest-list-label">{dest.name}</span>
                <Link to={`/destinations/${dest.id}`} className="dest-explore-btn">Explore</Link>
              </div>
            ))}
          </div>
        </div>

        {/* Discover More */}
        <div
          className="discover-more-container"
          style={{
            opacity: discoverBtnOpacity,
            visibility: discoverBtnOpacity === 0 ? 'hidden' : 'visible'
          }}
        >
          <Link to="/destinations" className="discover-more-link">Discover<br /><em>more</em></Link>
        </div>
      </div>

      {/* Text overlay */}
      <div className="scroll-content">
        <div className="hero-viewport">

          {/* CENTER: ELEVÉ title */}
          <div
            className="hero-center-title"
            style={{
              opacity: titleOpacity,
              transform: `translate(-50%, -50%) scale(${titleScale}) translateY(${titleTranslateY}px)`
            }}
          >
            <span className="center-title-text">ELEVÉ</span>
          </div>

          {/* LEFT: Main heading */}
          <div
            className="hero-text-left"
            style={{
              opacity: leftOpacity,
              transform: `scale(${leftScale}) translateY(${leftTranslateY}px)`
            }}
          >
            <h1 className="hero-large-text">We are<br /><em>exploration</em></h1>
          </div>

          {/* RIGHT: Secondary heading */}
          <div
            className="hero-text-right"
            style={{
              opacity: rightOpacity,
              transform: `scale(${rightScale}) translateY(${rightTranslateY}px)`
            }}
          >
            <h1 className="hero-large-text">We are<br /><em>distinction</em></h1>
          </div>

          {/* BOTTOM LEFT: Tagline & description */}
          <div
            className="hero-text-bottom-left"
            style={{
              opacity: bottomLeftOpacity,
              transform: `translateY(${bottomLeftTranslateY}px)`
            }}
          >
            <h3 className="hero-tagline">Your freedom to<br />explore the cosmos</h3>
            <p className="hero-desc">
              Every journey is designed around your comfort, time, and ambitions — so you can focus on what truly
              matters, while we take care of everything&nbsp;else.
            </p>
          </div>

          {/* BOTTOM RIGHT: Scroll hint */}
          <div className="hero-text-bottom-right" style={{ opacity: bottomRightOpacity }}>
            <div className="scroll-cue">
              <span className="scroll-cue-arrow">↓</span>
              <span className="scroll-cue-label">SCROLL DOWN</span>
              <span className="scroll-cue-sub">TO START THE JOURNEY</span>
            </div>
          </div>

          {/* BOTTOM CENTER: CTA Button */}
          <div
            className="hero-cta-center"
            style={{
              opacity: ctaOpacity,
              transform: `translateX(-50%) translateY(${ctaTranslateY}px)`
            }}
          >
            <Link to="/book-tour" className="cta-btn">
              <span className="cta-label">Book a Tour</span>
              <span className="cta-icon-circle">
                <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="white" viewBox="0 0 16 16">
                  <path d="M6.428 1.151C6.708.591 7.213 0 8 0s1.292.592 1.572 1.151C9.861 1.73 10 2.431 10 3v3.691l5.17 2.585a1.5 1.5 0 0 1 .83 1.342V12a.5.5 0 0 1-.582.493l-5.507-.918-.375 2.253 1.318 1.318A.5.5 0 0 1 10.5 16h-5a.5.5 0 0 1-.354-.854l1.319-1.318-.376-2.253-5.507.918A.5.5 0 0 1 0 12v-1.382a1.5 1.5 0 0 1 .83-1.342L6 6.691V3c0-.568.14-1.271.428-1.849Z" />
                </svg>
              </span>
            </Link>
          </div>

        </div>

        {/* Subsequent viewports (scroll space) */}
        <div className="hero-viewport"></div>
        <div className="hero-viewport"></div>
      </div>
    </section>
  )
}
