// src/pages/Destinations/DestinationDetails.jsx
import { useState, useEffect, useRef } from 'react'
import { useParams, Link } from 'react-router-dom'
import { getDestinationById } from '../../data/destinations.js'
import './DestinationDetails.css'

export default function DestinationDetails() {
  const { id } = useParams()
  const dest = getDestinationById(id)
  const [activeImageIndex, setActiveImageIndex] = useState(0)
  const [isTransitioning, setIsTransitioning] = useState(false)
  const isPausedRef = useRef(false)
  const intervalRef = useRef(null)

  const transitionToImage = (index) => {
    setIsTransitioning(true)
    setTimeout(() => {
      setActiveImageIndex(index)
      requestAnimationFrame(() => setIsTransitioning(false))
    }, 500)
  }

  const nextImage = () => {
    if (!dest?.images) return
    transitionToImage((activeImageIndex + 1) % dest.images.length)
  }

  const setActiveImage = (i) => {
    if (i === activeImageIndex) return
    isPausedRef.current = true
    transitionToImage(i)
    setTimeout(() => { isPausedRef.current = false }, 5000)
  }

  useEffect(() => {
    if (!dest?.images || dest.images.length <= 1) return
    intervalRef.current = setInterval(() => {
      if (!isPausedRef.current) {
        setActiveImageIndex(prev => (prev + 1) % dest.images.length)
      }
    }, 4000)
    return () => clearInterval(intervalRef.current)
  }, [dest])

  if (!dest) {
    return (
      <div className="container py-5 mt-5 text-center">
        <div className="spinner-border text-primary" role="status">
          <span className="visually-hidden">Loading...</span>
        </div>
      </div>
    )
  }

  const activeImage = dest.images?.[activeImageIndex] || dest.imageUrl

  return (
    <div className="container py-5 mt-5">
      <div className="row g-5">
        {/* LEFT: Gallery */}
        <div className="col-lg-8">
          {/* Main Image */}
          <div
            className="gallery-container overflow-hidden mb-4"
            style={{ cursor: 'pointer', position: 'relative' }}
          >
            <img
              src={activeImage}
              alt={dest.name}
              className={`main-image w-100 h-100 object-fit-cover${isTransitioning ? ' fade-out' : ''}`}
            />
          </div>

          {/* Thumbnails */}
          <div className="thumbnail-scroll d-flex gap-3 overflow-auto pb-3">
            {dest.images?.map((img, i) => (
              <button
                key={i}
                className={`thumbnail-btn rounded-3${i === activeImageIndex ? ' active' : ''}`}
                onClick={() => setActiveImage(i)}
                aria-label={`View image ${i + 1}`}
              >
                <img src={img} alt={`Thumbnail ${i + 1}`} className="w-100 h-100 object-fit-cover" />
              </button>
            ))}
          </div>
        </div>

        {/* RIGHT: Details */}
        <div className="col-lg-4">
          <div className="d-flex justify-content-between align-items-center mb-3">
            <h1 className="h2 fw-bold mb-0">{dest.name}</h1>
            <span className="rating-badge">
              <i className="bi bi-star-fill me-1"></i>{dest.rating}
            </span>
          </div>
          <p className="text-muted mb-4"><i className="bi bi-geo-alt-fill me-1"></i>{dest.location}</p>
          <p className="mb-4 text-secondary">{dest.description}</p>

          {/* Highlights */}
          <h5 className="fw-bold mb-3">Highlights</h5>
          <ul className="list-unstyled d-flex flex-wrap gap-2 mb-4">
            {dest.highlights?.map(h => (
              <li key={h}><span className="highlight-tag">{h}</span></li>
            ))}
          </ul>

          {/* Tourism Info */}
          <div className="info-card p-4 mb-4">
            <div className="row g-3">
              {[
                ['DURATION', dest.duration],
                ['BEST TIME', dest.tourismInfo?.bestTimeToVisit],
                ['LANGUAGE', dest.tourismInfo?.language],
                ['CURRENCY', dest.tourismInfo?.currency]
              ].map(([label, value]) => (
                <div key={label} className="col-6">
                  <small className="text-muted d-block text-uppercase fw-bold mb-1" style={{ fontSize: '0.75rem', letterSpacing: '1px' }}>{label}</small>
                  <span className="fw-medium text-dark">{value}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Book CTA */}
          <div className="book-cta-card d-flex align-items-center justify-content-between p-4">
            <div>
              <span className="d-block small mb-1">Starting from</span>
              <span className="h2 price-amount fw-bold mb-0">${dest.price?.toLocaleString()}</span>
              <span className="small"> / person</span>
            </div>
            <Link
              to={`/book-tour?destinationId=${dest.id}`}
              className="book-cta-btn"
            >
              Book Now
            </Link>
          </div>
        </div>
      </div>

      {/* Customer Reviews */}
      <div className="row mt-5 pt-5">
        <div className="col-12">
          <h3 className="fw-bold mb-4">Customer Reviews</h3>
          <div className="reviews-container position-relative overflow-hidden w-100">
            <div className="fade-overlay-left"></div>
            <div className="fade-overlay-right"></div>
            <div className="reviews-track d-flex gap-4">
              {/* Original + duplicate for infinite loop */}
              {[...dest.reviews, ...dest.reviews].map((review, idx) => (
                <div key={idx} className="review-card p-4 rounded-4 bg-white shadow-sm border col-md-4 flex-shrink-0">
                  <div className="d-flex align-items-center mb-3">
                    <div className="avatar-circle rounded-circle bg-light d-flex align-items-center justify-content-center me-3 fw-bold text-primary fs-5"
                      style={{ width: '50px', height: '50px' }}>
                      {review.author.charAt(0)}
                    </div>
                    <div>
                      <h6 className="fw-bold mb-0">{review.author}</h6>
                      <small className="text-muted">{review.date}</small>
                    </div>
                  </div>
                  <div className="mb-2 text-warning">
                    {[1, 2, 3, 4, 5].map(star => (
                      <i key={star} className={`bi ${star <= review.rating ? 'bi-star-fill' : 'bi-star'}`}></i>
                    ))}
                  </div>
                  <p className="text-secondary small mb-0">"{review.text}"</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// src/app/pages/destinations/destination-details/destination-details.component.ts
import { Component, ChangeDetectionStrategy, inject, signal, computed, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { DestinationsService } from '../destinations.service';
import { toSignal } from '@angular/core/rxjs-interop';
import { map, switchMap } from 'rxjs/operators';

@Component({
    selector: 'app-destination-details',
    imports: [CommonModule, RouterLink],
    templateUrl: './destination-details.component.html',
    styleUrl: './destination-details.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class DestinationDetailsComponent implements OnInit, OnDestroy {
    private route = inject(ActivatedRoute);
    private destinationsService = inject(DestinationsService);
    private intervalId: any;

    // Get ID from route params and fetch destination
    destination = toSignal(
        this.route.paramMap.pipe(
            map(params => Number(params.get('id'))),
            switchMap(id => this.destinationsService.getDestinationById(id))
        )
    );

    activeImageIndex = signal(0);
    isPaused = signal(false);
    isTransitioning = signal(false);

    activeImage = computed(() => {
        const dest = this.destination();
        if (!dest || !dest.images || dest.images.length === 0) return '';
        return dest.images[this.activeImageIndex()];
    });

    ngOnInit() {
        this.startSlideShow();
    }

    ngOnDestroy() {
        this.clearSlideShow();
    }

    startSlideShow() {
        this.intervalId = setInterval(() => {
            if (!this.isPaused()) {
                this.nextImage();
            }
        }, 4000); // 4 seconds per slide
    }

    clearSlideShow() {
        if (this.intervalId) {
            clearInterval(this.intervalId);
        }
    }

    nextImage() {
        const dest = this.destination();
        if (!dest || !dest.images) return;

        const nextIndex = (this.activeImageIndex() + 1) % dest.images.length;
        this.transitionToImage(nextIndex);
    }

    setActiveImage(index: number) {
        if (this.activeImageIndex() === index) return;

        this.isPaused.set(true);
        this.transitionToImage(index);

        // Resume after 5 seconds of inactivity
        setTimeout(() => {
            this.isPaused.set(false);
        }, 5000);
    }

    transitionToImage(index: number) {
        this.isTransitioning.set(true);

        // Wait for fade out
        setTimeout(() => {
            this.activeImageIndex.set(index);
            // Wait a tiny bit for render cycle then fade in
            requestAnimationFrame(() => {
                this.isTransitioning.set(false);
            });
        }, 500); // Match CSS transition duration
    }

    togglePause(paused: boolean) {
        this.isPaused.set(paused);
    }

}

@if (destination(); as dest) {
<div class="container py-5 fade-in" style="margin-top: 85px;">
    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb" class="mb-4">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a routerLink="/" class="text-decoration-none text-muted">Home</a></li>
            <li class="breadcrumb-item"><a routerLink="/destinations"
                    class="text-decoration-none text-muted">Destinations</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ dest.name }}</li>
        </ol>
    </nav>

    <div class="row g-5">
        <!-- Image Gallery Section -->
        <div class="col-lg-7">
            <div class="gallery-container mb-4 position-relative overflow-hidden rounded-4 shadow-sm"
                (mouseenter)="togglePause(true)" (mouseleave)="togglePause(false)">
                <img [src]="activeImage() || dest.imageUrl" [alt]="dest.name" class="main-image w-100 object-fit-cover"
                    [class.fade-out]="isTransitioning()" style="height: 500px;">
            </div>

            <div class="d-flex gap-3 overflow-auto pb-2 thumbnail-scroll">
                @for (img of dest.images; track $index) {
                <button class="btn p-0 border-0 thumbnail-btn" [class.active]="activeImageIndex() === $index"
                    (click)="setActiveImage($index)">
                    <img [src]="img" [alt]="dest.name + ' view ' + ($index + 1)" class="rounded-3 object-fit-cover"
                        style="width: 100px; height: 70px;">
                </button>
                }
            </div>
        </div>

        <!-- Details Section -->
        <div class="col-lg-5">
            <div class="badge bg-primary-subtle text-primary mb-3 px-3 py-2 rounded-pill">{{ dest.type }}</div>
            <h1 class="display-4 fw-bold mb-3">{{ dest.name }}</h1>
            <div class="d-flex align-items-center mb-4">
                <i class="bi bi-geo-alt text-primary me-2"></i>
                <span class="text-muted me-4">{{ dest.location }}</span>
                <i class="bi bi-star-fill text-warning me-2"></i>
                <span class="fw-bold">{{ dest.rating }}</span>
            </div>

            <p class="lead text-secondary mb-4">{{ dest.description }}</p>

            <div class="card border-0 bg-light rounded-4 mb-4">
                <div class="card-body p-4">
                    <h5 class="fw-bold mb-3">Trip Highlights</h5>
                    <ul class="list-unstyled mb-0">
                        @for (highlight of dest.highlights; track highlight) {
                        <li class="mb-2 d-flex align-items-start">
                            <i class="bi bi-check-circle-fill text-success me-2 mt-1"></i>
                            <span>{{ highlight }}</span>
                        </li>
                        }
                    </ul>
                </div>
            </div>

            <div class="bg-white border rounded-4 p-4 mb-4 shadow-sm">
                <h5 class="fw-bold mb-3">Tourism Info</h5>
                <div class="row g-3">
                    <div class="col-6">
                        <small class="text-muted d-block uppercase fw-bold"
                            style="font-size: 0.75rem; letter-spacing: 1px;">DURATION</small>
                        <span>{{ dest.duration }}</span>
                    </div>
                    <div class="col-6">
                        <small class="text-muted d-block uppercase fw-bold"
                            style="font-size: 0.75rem; letter-spacing: 1px;">BEST TIME</small>
                        <span>{{ dest.tourismInfo.bestTimeToVisit }}</span>
                    </div>
                    <div class="col-6">
                        <small class="text-muted d-block uppercase fw-bold"
                            style="font-size: 0.75rem; letter-spacing: 1px;">LANGUAGE</small>
                        <span>{{ dest.tourismInfo.language }}</span>
                    </div>
                    <div class="col-6">
                        <small class="text-muted d-block uppercase fw-bold"
                            style="font-size: 0.75rem; letter-spacing: 1px;">CURRENCY</small>
                        <span>{{ dest.tourismInfo.currency }}</span>
                    </div>
                </div>
            </div>

            <div class="d-flex align-items-center justify-content-between bg-dark text-white p-4 rounded-4 shadow-lg">
                <div>
                    <span class="d-block text-white-50 small">Starting from</span>
                    <span class="h2 fw-bold mb-0">{{ dest.price | currency }}</span>
                    <span class="text-white-50 small"> / person</span>
                </div>
                <button routerLink="/book-tour" [queryParams]="{ destinationId: dest.id }"
                    class="btn btn-light rounded-pill px-5 py-3 fw-bold">Book Now</button>
            </div>
        </div>
    </div>

    <!-- Customer Reviews Section -->
    <div class="row mt-5 pt-5">
        <div class="col-12">
            <h3 class="fw-bold mb-4">Customer Reviews</h3>

            <div class="reviews-container position-relative overflow-hidden w-100">
                <!-- Fade Gradients -->
                <div class="fade-overlay-left"></div>
                <div class="fade-overlay-right"></div>

                <div class="reviews-track d-flex gap-4">
                    <!-- Original List -->
                    @for (review of dest.reviews; track $index) {
                    <div class="review-card p-4 rounded-4 bg-white shadow-sm border col-md-4 flex-shrink-0">
                        <div class="d-flex align-items-center mb-3">
                            <div class="avatar-circle rounded-circle bg-light d-flex align-items-center justify-content-center me-3 fw-bold text-primary fs-5"
                                style="width: 50px; height: 50px;">
                                {{ review.author.charAt(0) }}
                            </div>
                            <div>
                                <h6 class="fw-bold mb-0">{{ review.author }}</h6>
                                <small class="text-muted">{{ review.date }}</small>
                            </div>
                        </div>
                        <div class="mb-2 text-warning">
                            @for (star of [1,2,3,4,5]; track star) {
                            <i class="bi" [class.bi-star-fill]="star <= review.rating"
                                [class.bi-star]="star > review.rating"></i>
                            }
                        </div>
                        <p class="text-secondary small mb-0">"{{ review.text }}"</p>
                    </div>
                    }
                    <!-- Duplicate List for Infinite Loop -->
                    @for (review of dest.reviews; track $index) {
                    <div class="review-card p-4 rounded-4 bg-white shadow-sm border col-md-4 flex-shrink-0">
                        <div class="d-flex align-items-center mb-3">
                            <div class="avatar-circle rounded-circle bg-light d-flex align-items-center justify-content-center me-3 fw-bold text-primary fs-5"
                                style="width: 50px; height: 50px;">
                                {{ review.author.charAt(0) }}
                            </div>
                            <div>
                                <h6 class="fw-bold mb-0">{{ review.author }}</h6>
                                <small class="text-muted">{{ review.date }}</small>
                            </div>
                        </div>
                        <div class="mb-2 text-warning">
                            @for (star of [1,2,3,4,5]; track star) {
                            <i class="bi" [class.bi-star-fill]="star <= review.rating"
                                [class.bi-star]="star > review.rating"></i>
                            }
                        </div>
                        <p class="text-secondary small mb-0">"{{ review.text }}"</p>
                    </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
} @else {
<div class="container py-5 mt-5 text-center">
    <div class="spinner-border text-primary" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
</div>
}
