// src/app/pages/payment/payment.component.ts
import { Component, ChangeDetectionStrategy, inject, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { DestinationsService } from '../destinations/destinations.service';

interface PaymentBookingData {
    destinationId: number;
    destinationName: string;
    date: string;
    guests: number;
    name: string;
    email: string;
    phone: string;
    specialRequests: string;
    totalPrice: number;
    couponCode?: string;
    discountAmount?: number;
}

@Component({
    selector: 'app-payment',
    imports: [CommonModule, ReactiveFormsModule, RouterLink],
    templateUrl: './payment.component.html',
    styleUrl: './payment.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class PaymentComponent implements OnInit {
    private fb = inject(FormBuilder);
    private router = inject(Router);
    private destinationsService = inject(DestinationsService);

    bookingData = signal<PaymentBookingData | null>(null);
    isProcessing = signal(false);
    paymentError = signal<string | null>(null);

    paymentForm = this.fb.group({
        cardholderName: ['', Validators.required],
        cardNumber: ['', [Validators.required, Validators.pattern(/^\d{4}\s?\d{4}\s?\d{4}\s?\d{4}$/)]],
        expiryDate: ['', [Validators.required, Validators.pattern(/^(0[1-9]|1[0-2])\/\d{2}$/)]],
        cvv: ['', [Validators.required, Validators.pattern(/^\d{3,4}$/)]]
    });

    ngOnInit() {
        const nav = this.router.getCurrentNavigation();
        const state = nav?.extras?.state ?? (typeof history !== 'undefined' ? history.state : null);

        if (state?.['bookingData']) {
            this.bookingData.set(state['bookingData'] as PaymentBookingData);
        } else {
            // No booking data — redirect back
            this.router.navigate(['/book-tour']);
        }
    }

    formatCardNumber(event: Event) {
        const input = event.target as HTMLInputElement;
        let value = input.value.replace(/\D/g, '');
        value = value.substring(0, 16);
        const formatted = value.replace(/(\d{4})(?=\d)/g, '$1 ');
        input.value = formatted;
        this.paymentForm.get('cardNumber')?.setValue(formatted);
    }

    formatExpiry(event: Event) {
        const input = event.target as HTMLInputElement;
        let value = input.value.replace(/\D/g, '');
        value = value.substring(0, 4);
        if (value.length >= 3) {
            value = value.substring(0, 2) + '/' + value.substring(2);
        }
        input.value = value;
        this.paymentForm.get('expiryDate')?.setValue(value);
    }

    processPayment() {
        if (this.paymentForm.invalid) {
            this.paymentForm.markAllAsTouched();
            return;
        }

        const data = this.bookingData();
        if (!data) return;

        this.isProcessing.set(true);
        this.paymentError.set(null);

        const bookingRequest = {
            destinationId: data.destinationId,
            date: data.date,
            guests: data.guests,
            name: data.name,
            email: data.email,
            phone: data.phone,
            specialRequests: data.specialRequests
        };

        this.destinationsService.submitBooking(bookingRequest).subscribe({
            next: (success) => {
                this.isProcessing.set(false);
                if (success) {
                    this.router.navigate(['/book-tour'], { state: { paymentSuccess: true } });
                }
            },
            error: () => {
                this.isProcessing.set(false);
                this.paymentError.set('Payment failed. Please try again.');
            }
        });
    }
}

<div class="container py-5 mt-5">
    <div class="text-center mb-5 pt-4">
        <h1 class="display-4 fw-bold">Payment</h1>
        <p class="lead text-muted mt-2">Complete your payment to confirm the booking.</p>
    </div>

    @if (bookingData(); as data) {
    <div class="row g-5">
        <!-- Left Column: Payment Form -->
        <div class="col-lg-7">
            <div class="card border-0 shadow-lg rounded-5 overflow-hidden h-100 pop-card">
                <div class="card-body p-4 p-md-5">
                    <h4 class="fw-bold mb-4 text-theme">
                        <i class="bi bi-credit-card me-2"></i>Card Details
                    </h4>

                    @if (paymentError()) {
                    <div class="alert alert-danger rounded-4 mb-4 d-flex align-items-center" role="alert">
                        <i class="bi bi-exclamation-triangle-fill me-2"></i>
                        {{ paymentError() }}
                    </div>
                    }

                    <form [formGroup]="paymentForm" (ngSubmit)="processPayment()">
                        <!-- Cardholder Name -->
                        <div class="mb-4">
                            <label for="cardholderName"
                                class="form-label fw-bold small text-uppercase text-muted">Cardholder Name</label>
                            <div class="input-group">
                                <span class="input-group-text bg-light border-0 rounded-start-pill ps-3">
                                    <i class="bi bi-person text-theme"></i>
                                </span>
                                <input type="text" id="cardholderName"
                                    class="form-control form-control-lg border-0 bg-light rounded-end-pill shadow-sm-hover"
                                    formControlName="cardholderName" placeholder="Name on card">
                            </div>
                            @if (paymentForm.get('cardholderName')?.invalid &&
                            paymentForm.get('cardholderName')?.touched) {
                            <div class="text-danger small mt-1 ps-3">Cardholder name is required.</div>
                            }
                        </div>

                        <!-- Card Number -->
                        <div class="mb-4">
                            <label for="cardNumber" class="form-label fw-bold small text-uppercase text-muted">Card
                                Number</label>
                            <div class="input-group">
                                <span class="input-group-text bg-light border-0 rounded-start-pill ps-3">
                                    <i class="bi bi-credit-card-2-front text-theme"></i>
                                </span>
                                <input type="text" id="cardNumber"
                                    class="form-control form-control-lg border-0 bg-light rounded-end-pill shadow-sm-hover"
                                    formControlName="cardNumber" placeholder="0000 0000 0000 0000" maxlength="19"
                                    (input)="formatCardNumber($event)">
                            </div>
                            @if (paymentForm.get('cardNumber')?.invalid && paymentForm.get('cardNumber')?.touched) {
                            <div class="text-danger small mt-1 ps-3">Please enter a valid 16-digit card number.</div>
                            }
                        </div>

                        <div class="row g-4 mb-4">
                            <!-- Expiry -->
                            <div class="col-md-6">
                                <label for="expiryDate"
                                    class="form-label fw-bold small text-uppercase text-muted">Expiry Date</label>
                                <div class="input-group">
                                    <span class="input-group-text bg-light border-0 rounded-start-pill ps-3">
                                        <i class="bi bi-calendar3 text-theme"></i>
                                    </span>
                                    <input type="text" id="expiryDate"
                                        class="form-control form-control-lg border-0 bg-light rounded-end-pill shadow-sm-hover"
                                        formControlName="expiryDate" placeholder="MM/YY" maxlength="5"
                                        (input)="formatExpiry($event)">
                                </div>
                                @if (paymentForm.get('expiryDate')?.invalid && paymentForm.get('expiryDate')?.touched) {
                                <div class="text-danger small mt-1 ps-3">Enter a valid expiry (MM/YY).</div>
                                }
                            </div>

                            <!-- CVV -->
                            <div class="col-md-6">
                                <label for="cvv" class="form-label fw-bold small text-uppercase text-muted">CVV</label>
                                <div class="input-group">
                                    <span class="input-group-text bg-light border-0 rounded-start-pill ps-3">
                                        <i class="bi bi-lock text-theme"></i>
                                    </span>
                                    <input type="password" id="cvv"
                                        class="form-control form-control-lg border-0 bg-light rounded-end-pill shadow-sm-hover"
                                        formControlName="cvv" placeholder="•••" maxlength="4">
                                </div>
                                @if (paymentForm.get('cvv')?.invalid && paymentForm.get('cvv')?.touched) {
                                <div class="text-danger small mt-1 ps-3">Enter a valid 3 or 4 digit CVV.</div>
                                }
                            </div>
                        </div>

                        <!-- Secure payment notice -->
                        <div class="d-flex align-items-center text-muted small mb-4">
                            <i class="bi bi-shield-lock-fill me-2 text-success"></i>
                            Your payment information is secure and encrypted.
                        </div>

                        <!-- Pay Now Button -->
                        <button type="submit"
                            class="btn btn-theme w-100 rounded-pill py-3 fw-bold shadow-lg d-flex justify-content-between align-items-center px-4"
                            [disabled]="isProcessing()">
                            @if (isProcessing()) {
                            <span>Processing Payment...</span>
                            <div class="spinner-border spinner-border-sm text-white" role="status"></div>
                            } @else {
                            <span><i class="bi bi-lock-fill me-2"></i>Pay Now</span>
                            <span class="bg-white text-theme px-2 py-1 rounded-pill small fw-bold">
                                {{ data.totalPrice | currency }}
                            </span>
                            }
                        </button>
                    </form>
                </div>
            </div>
        </div>

        <!-- Right Column: Booking Summary -->
        <div class="col-lg-5">
            <div class="card border-0 shadow-lg rounded-5 overflow-hidden card-spotlight text-white pop-card">
                <div class="card-body p-4 p-md-5 position-relative">
                    <div class="position-absolute top-0 end-0 p-3 opacity-25">
                        <i class="bi bi-receipt display-1"></i>
                    </div>
                    <h3 class="fw-bold mb-4">Booking Summary</h3>

                    <div class="summary-row">
                        <span class="summary-label"><i class="bi bi-geo-alt me-2"></i>Destination</span>
                        <span class="summary-value">{{ data.destinationName }}</span>
                    </div>
                    <div class="summary-row">
                        <span class="summary-label"><i class="bi bi-calendar-event me-2"></i>Date</span>
                        <span class="summary-value">{{ data.date }}</span>
                    </div>
                    <div class="summary-row">
                        <span class="summary-label"><i class="bi bi-people me-2"></i>Guests</span>
                        <span class="summary-value">{{ data.guests }}</span>
                    </div>
                    <div class="summary-row">
                        <span class="summary-label"><i class="bi bi-person me-2"></i>Name</span>
                        <span class="summary-value">{{ data.name }}</span>
                    </div>
                    <div class="summary-row">
                        <span class="summary-label"><i class="bi bi-envelope me-2"></i>Email</span>
                        <span class="summary-value">{{ data.email }}</span>
                    </div>

                    @if (data.couponCode) {
                    <div class="summary-row text-warning">
                        <span class="summary-label"><i class="bi bi-tag me-2"></i>Coupon</span>
                        <span class="summary-value">{{ data.couponCode }} (-{{ data.discountAmount | currency }})</span>
                    </div>
                    }

                    <hr class="border-white opacity-50 my-3">
                    <div class="d-flex justify-content-between align-items-center">
                        <span class="h5 mb-0 opacity-75">Total</span>
                        <span class="h2 fw-bold mb-0">{{ data.totalPrice | currency }}</span>
                    </div>
                </div>
            </div>

            <!-- Back to Booking Link -->
            <a routerLink="/book-tour"
                class="btn btn-outline-secondary w-100 rounded-pill py-3 fw-bold mt-4 d-flex align-items-center justify-content-center">
                <i class="bi bi-arrow-left me-2"></i>Back to Booking
            </a>

            <!-- Accepted Cards -->
            <div class="text-center mt-4">
                <p class="text-muted small mb-2">We accept</p>
                <div class="d-flex justify-content-center gap-3">
                    <span class="badge bg-light text-dark rounded-pill px-3 py-2 fw-bold">
                        <i class="bi bi-credit-card me-1"></i>Visa
                    </span>
                    <span class="badge bg-light text-dark rounded-pill px-3 py-2 fw-bold">
                        <i class="bi bi-credit-card me-1"></i>Mastercard
                    </span>
                    <span class="badge bg-light text-dark rounded-pill px-3 py-2 fw-bold">
                        <i class="bi bi-credit-card me-1"></i>Amex
                    </span>
                </div>
            </div>
        </div>
    </div>
    }
</div>

// src/pages/Payment/Payment.jsx
import { useState } from 'react'
import { useLocation, useNavigate, Link } from 'react-router-dom'
import './Payment.css'

function formatCardNumber(value) {
  return value.replace(/\D/g, '').replace(/(\d{4})/g, '$1 ').trim().slice(0, 19)
}

function formatExpiry(value) {
  const digits = value.replace(/\D/g, '')
  if (digits.length >= 3) return digits.slice(0, 2) + '/' + digits.slice(2, 4)
  return digits
}

export default function Payment() {
  const location = useLocation()
  const navigate = useNavigate()
  const bookingData = location.state?.bookingData || location.state?.bookingDetails

  const [form, setForm] = useState({
    cardholderName: '',
    cardNumber: '',
    expiryDate: '',
    cvv: ''
  })
  const [touched, setTouched] = useState({})
  const [paymentError, setPaymentError] = useState('')
  const [isProcessing, setIsProcessing] = useState(false)
  const [paymentSuccess, setPaymentSuccess] = useState(false)

  const validate = () => {
    const errs = {}
    if (!form.cardholderName.trim()) errs.cardholderName = 'Cardholder name is required.'
    if (!/^\d{4} \d{4} \d{4} \d{4}$/.test(form.cardNumber)) errs.cardNumber = 'Please enter a valid 16-digit card number.'
    if (!/^\d{2}\/\d{2}$/.test(form.expiryDate)) errs.expiryDate = 'Enter a valid expiry (MM/YY).'
    if (!/^\d{3,4}$/.test(form.cvv)) errs.cvv = 'Enter a valid 3 or 4 digit CVV.'
    return errs
  }

  const errors = validate()
  const isValid = Object.keys(errors).length === 0

  const handleChange = (e) => {
    let { name, value } = e.target
    if (name === 'cardNumber') value = formatCardNumber(value)
    if (name === 'expiryDate') value = formatExpiry(value)
    setForm(prev => ({ ...prev, [name]: value }))
  }

  const handleBlur = (field) => setTouched(prev => ({ ...prev, [field]: true }))

  const handleSubmit = (e) => {
    e.preventDefault()
    setTouched({ cardholderName: true, cardNumber: true, expiryDate: true, cvv: true })
    if (!isValid) return

    setIsProcessing(true)
    setPaymentError('')
    setTimeout(() => {
      setIsProcessing(false)
      navigate('/book-tour', { state: { paymentSuccess: true } })
    }, 2000)
  }

  if (!bookingData) {
    return (
      <div className="container py-5 mt-5 text-center">
        <h2 className="fw-bold mb-3">No Booking Found</h2>
        <p className="text-muted">Please start a new booking first.</p>
        <Link to="/book-tour" className="btn btn-primary rounded-pill px-5 mt-3">Book a Tour</Link>
      </div>
    )
  }

  if (paymentSuccess) {
    return (
      <div className="container py-5 mt-5 text-center">
        <div className="success-card mx-auto p-5 rounded-4 shadow">
          <div className="success-icon mb-4">✓</div>
          <h2 className="fw-bold mb-2">Booking Confirmed!</h2>
          <p className="text-muted mb-4">Your trip to <strong>{bookingData.destinationName}</strong> is confirmed.</p>
          <p className="small text-muted">A confirmation has been sent to {bookingData.email}</p>
          <Link to="/" className="btn btn-primary rounded-pill px-5 mt-4">Back to Home</Link>
        </div>
      </div>
    )
  }

  return (
    <div className="container py-5 mt-5">
      <div className="text-center mb-5 pt-4">
        <h1 className="display-4 fw-bold">Payment</h1>
        <p className="lead text-muted mt-2">Complete your payment to confirm the booking.</p>
      </div>

      <div className="row g-5">
        {/* Card Details */}
        <div className="col-lg-7">
          <div className="card border-0 shadow-lg rounded-5 overflow-hidden pop-card">
            <div className="card-body p-4 p-md-5">
              <h4 className="fw-bold mb-4 text-theme">
                <i className="bi bi-credit-card me-2"></i>Card Details
              </h4>

              {paymentError && (
                <div className="alert alert-danger rounded-4 mb-4 d-flex align-items-center">
                  <i className="bi bi-exclamation-triangle-fill me-2"></i>{paymentError}
                </div>
              )}

              <form onSubmit={handleSubmit} noValidate>
                {/* Cardholder Name */}
                <div className="mb-4">
                  <label className="form-label fw-bold small text-uppercase text-muted">Cardholder Name</label>
                  <div className="input-group">
                    <span className="input-group-text bg-light border-0 rounded-start-pill ps-3">
                      <i className="bi bi-person text-theme"></i>
                    </span>
                    <input type="text" name="cardholderName" className="form-control form-control-lg border-0 bg-light rounded-end-pill"
                      value={form.cardholderName} onChange={handleChange} onBlur={() => handleBlur('cardholderName')}
                      placeholder="Name on card" />
                  </div>
                  {touched.cardholderName && errors.cardholderName &&
                    <div className="text-danger small mt-1 ps-3">{errors.cardholderName}</div>}
                </div>

                {/* Card Number */}
                <div className="mb-4">
                  <label className="form-label fw-bold small text-uppercase text-muted">Card Number</label>
                  <div className="input-group">
                    <span className="input-group-text bg-light border-0 rounded-start-pill ps-3">
                      <i className="bi bi-credit-card-2-front text-theme"></i>
                    </span>
                    <input type="text" name="cardNumber" className="form-control form-control-lg border-0 bg-light rounded-end-pill"
                      value={form.cardNumber} onChange={handleChange} onBlur={() => handleBlur('cardNumber')}
                      placeholder="0000 0000 0000 0000" maxLength="19" />
                  </div>
                  {touched.cardNumber && errors.cardNumber &&
                    <div className="text-danger small mt-1 ps-3">{errors.cardNumber}</div>}
                </div>

                <div className="row g-4 mb-4">
                  {/* Expiry */}
                  <div className="col-md-6">
                    <label className="form-label fw-bold small text-uppercase text-muted">Expiry Date</label>
                    <div className="input-group">
                      <span className="input-group-text bg-light border-0 rounded-start-pill ps-3">
                        <i className="bi bi-calendar3 text-theme"></i>
                      </span>
                      <input type="text" name="expiryDate" className="form-control form-control-lg border-0 bg-light rounded-end-pill"
                        value={form.expiryDate} onChange={handleChange} onBlur={() => handleBlur('expiryDate')}
                        placeholder="MM/YY" maxLength="5" />
                    </div>
                    {touched.expiryDate && errors.expiryDate &&
                      <div className="text-danger small mt-1 ps-3">{errors.expiryDate}</div>}
                  </div>

                  {/* CVV */}
                  <div className="col-md-6">
                    <label className="form-label fw-bold small text-uppercase text-muted">CVV</label>
                    <div className="input-group">
                      <span className="input-group-text bg-light border-0 rounded-start-pill ps-3">
                        <i className="bi bi-lock text-theme"></i>
                      </span>
                      <input type="password" name="cvv" className="form-control form-control-lg border-0 bg-light rounded-end-pill"
                        value={form.cvv} onChange={handleChange} onBlur={() => handleBlur('cvv')}
                        placeholder="•••" maxLength="4" />
                    </div>
                    {touched.cvv && errors.cvv &&
                      <div className="text-danger small mt-1 ps-3">{errors.cvv}</div>}
                  </div>
                </div>

                <div className="d-flex align-items-center text-muted small mb-4">
                  <i className="bi bi-shield-lock-fill me-2 text-success"></i>
                  Your payment information is secure and encrypted.
                </div>

                <button type="submit" className="btn btn-primary btn-lg w-100 rounded-pill py-3 fw-bold" disabled={isProcessing}>
                  {isProcessing ? (
                    <><span className="spinner-border spinner-border-sm me-2"></span>Processing Payment...</>
                  ) : (
                    <><i className="bi bi-lock-fill me-2"></i>Pay Now — ${bookingData.totalPrice?.toFixed(0)}</>
                  )}
                </button>
              </form>
            </div>
          </div>
        </div>

        {/* Booking Summary */}
        <div className="col-lg-5">
          <div className="card border-0 shadow-sm rounded-5 overflow-hidden">
            <div className="card-body p-4">
              <h4 className="fw-bold mb-4 text-theme">
                <i className="bi bi-receipt me-2"></i>Booking Summary
              </h4>
              <div className="summary-row d-flex justify-content-between py-2 border-bottom">
                <span className="text-muted">Destination</span>
                <span className="fw-bold">{bookingData.destinationName}</span>
              </div>
              <div className="summary-row d-flex justify-content-between py-2 border-bottom">
                <span className="text-muted">Traveler</span>
                <span>{bookingData.name}</span>
              </div>
              <div className="summary-row d-flex justify-content-between py-2 border-bottom">
                <span className="text-muted">Travel Date</span>
                <span>{bookingData.travelDate}</span>
              </div>
              <div className="summary-row d-flex justify-content-between py-2 border-bottom">
                <span className="text-muted">Travelers</span>
                <span>{bookingData.travelers}</span>
              </div>
              <div className="summary-row d-flex justify-content-between py-2 border-bottom">
                <span className="text-muted">Base Price</span>
                <span>${bookingData.basePrice?.toLocaleString()}</span>
              </div>
              {bookingData.discountAmount > 0 && (
                <div className="summary-row d-flex justify-content-between py-2 border-bottom text-success">
                  <span>Discount</span>
                  <span>-${bookingData.discountAmount?.toFixed(0)}</span>
                </div>
              )}
              <div className="summary-row d-flex justify-content-between py-2 border-bottom">
                <span className="text-muted">Taxes (12%)</span>
                <span>${bookingData.taxes?.toFixed(0)}</span>
              </div>
              <div className="d-flex justify-content-between py-3 fw-bold fs-5">
                <span>Total</span>
                <span>${bookingData.totalPrice?.toFixed(0)}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
