// src/app/components/header/header.component.ts
import { Component, ChangeDetectionStrategy, signal, inject, PLATFORM_ID } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { RouterLink, Router, NavigationEnd } from '@angular/router';
import { filter } from 'rxjs/operators';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-header',
  imports: [CommonModule, RouterLink],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '(window:scroll)': 'onWindowScroll()'
  }
})
export class HeaderComponent {
  private router = inject(Router);
  private platformId = inject(PLATFORM_ID);
  authService = inject(AuthService);

  isMenuOpen = signal(false);
  isScrolled = signal(false);
  isHome = signal(true);

  currentUser = this.authService.currentUser;

  constructor() {
    if (isPlatformBrowser(this.platformId)) {
      this.router.events.pipe(
        filter(event => event instanceof NavigationEnd)
      ).subscribe((event: NavigationEnd) => {
        const url = event.url;
        this.isHome.set(url === '/' || url === '/home' || url === '');
        this.checkScroll();
      });
    }
  }

  onWindowScroll() {
    this.checkScroll();
  }

  private checkScroll() {
    if (!isPlatformBrowser(this.platformId)) return;

    if (!this.isHome()) {
      // Non-home pages: always solid
      this.isScrolled.set(true);
    } else {
      // On home: stay transparent until the scroll animation container ends
      // The hero container is 300vh, scrollable distance is 300vh - 100vh = 200vh
      const heroContainer = document.querySelector('.hero-scroll-container') as HTMLElement;
      if (heroContainer) {
        const scrollableDist = heroContainer.scrollHeight - window.innerHeight;
        this.isScrolled.set(window.scrollY >= scrollableDist);
      } else {
        this.isScrolled.set(window.scrollY > 50);
      }
    }
  }

  toggleMenu() { this.isMenuOpen.update(v => !v); }
  closeMenu() { this.isMenuOpen.set(false); }

  login() { this.authService.login(); }
  logout() { this.authService.logout(); }
}

<header [class.scrolled]="isScrolled()" [class.is-home]="isHome()" class="d-flex align-items-center w-100">
    <div class="container-fluid px-4 px-md-5 d-flex align-items-center justify-content-between position-relative">

        <!-- Left: Navigation Links (original names) -->
        <nav class="desktop-nav" [class.mobile-open]="isMenuOpen()">
            <ul class="nav-menu list-unstyled mb-0 d-flex align-items-center gap-4">
                <li><a routerLink="/" (click)="closeMenu()">Home</a></li>
                <li><a routerLink="/destinations" (click)="closeMenu()">Destinations</a></li>
                <li><a routerLink="/activities" (click)="closeMenu()">Activities</a></li>
                <li><a routerLink="/contact" (click)="closeMenu()">Contact Us</a></li>

                <!-- Mobile Only Actions -->
                @if (!currentUser()) {
                <li class="d-lg-none mt-4"><a routerLink="/login" (click)="closeMenu()" class="pointer">Sign In</a></li>
                } @else {
                <li class="d-lg-none mt-4"><a routerLink="/profile" (click)="closeMenu()">My Profile</a></li>
                <li class="d-lg-none"><a (click)="logout(); closeMenu()" class="pointer">Logout</a></li>
                }
                <li class="d-lg-none"><a routerLink="/book-tour" (click)="closeMenu()" class="btn-book">Book a Tour</a>
                </li>
            </ul>
        </nav>

        <!-- Center: Logo (always visible in header) -->
        <div class="logo-wrapper">
            <a routerLink="/" class="logo">ELEVÉ</a>
        </div>

        <!-- Right: Auth & CTA -->
        <div class="header-actions d-flex align-items-center gap-3">

            <!-- Auth Section -->
            @if (!currentUser()) {
            <div class="auth-buttons d-none d-lg-flex align-items-center gap-3">
                <a routerLink="/login" class="nav-link pointer">Sign In</a>
            </div>
            } @else {
            <div class="user-profile d-none d-lg-flex align-items-center gap-2">
                <img [src]="currentUser()?.avatar" alt="User" class="avatar">
                <span class="username">{{ currentUser()?.name }}</span>
                <button (click)="logout()" class="btn-logout" aria-label="Logout">
                    <i class="bi bi-box-arrow-right"></i>
                </button>
            </div>
            }

            <a routerLink="/book-tour" class="btn-book text-decoration-none d-none d-lg-inline-block">Book a Tour</a>

            <!-- Mobile Burger -->
            <button class="burger d-lg-none" (click)="toggleMenu()" [class.open]="isMenuOpen()"
                aria-label="Toggle menu">
                <span></span>
                <span></span>
                <span></span>
            </button>
        </div>

    </div>
</header>

// src/components/Header/Header.jsx
import { useState, useEffect, useCallback } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext.jsx'
import './Header.css'

export default function Header() {
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const [isScrolled, setIsScrolled] = useState(false)
  const location = useLocation()
  const navigate = useNavigate()
  const { currentUser, logout } = useAuth()

  const isHome = location.pathname === '/' || location.pathname === '/home' || location.pathname === ''

  const checkScroll = useCallback(() => {
    if (!isHome) {
      setIsScrolled(true)
      return
    }
    const heroContainer = document.querySelector('.hero-scroll-container')
    if (heroContainer) {
      const scrollableDist = heroContainer.scrollHeight - window.innerHeight
      setIsScrolled(window.scrollY >= scrollableDist)
    } else {
      setIsScrolled(window.scrollY > 50)
    }
  }, [isHome])

  useEffect(() => {
    checkScroll()
    window.addEventListener('scroll', checkScroll, { passive: true })
    return () => window.removeEventListener('scroll', checkScroll)
  }, [checkScroll])

  // Close menu on route change
  useEffect(() => {
    setIsMenuOpen(false)
  }, [location.pathname])

  const handleLogout = () => {
    logout()
    navigate('/')
  }

  const headerClass = [
    'd-flex align-items-center w-100',
    isScrolled ? 'scrolled' : '',
    isHome ? 'is-home' : ''
  ].filter(Boolean).join(' ')

  return (
    <header className={headerClass} id="main-header">
      <div className="container-fluid px-4 px-md-5 d-flex align-items-center justify-content-between position-relative">

        {/* Left: Navigation Links */}
        <nav className={`desktop-nav${isMenuOpen ? ' mobile-open' : ''}`}>
          <ul className="nav-menu list-unstyled mb-0 d-flex align-items-center gap-4">
            <li><Link to="/" onClick={() => setIsMenuOpen(false)}>Home</Link></li>
            <li><Link to="/destinations" onClick={() => setIsMenuOpen(false)}>Destinations</Link></li>
            <li><Link to="/activities" onClick={() => setIsMenuOpen(false)}>Activities</Link></li>
            <li><Link to="/contact" onClick={() => setIsMenuOpen(false)}>Contact Us</Link></li>

            {/* Mobile Only Actions */}
            {!currentUser ? (
              <li className="d-lg-none mt-4">
                <Link to="/login" onClick={() => setIsMenuOpen(false)} className="pointer">Sign In</Link>
              </li>
            ) : (
              <>
                <li className="d-lg-none mt-4">
                  <Link to="/profile" onClick={() => setIsMenuOpen(false)}>My Profile</Link>
                </li>
                <li className="d-lg-none">
                  <span onClick={() => { handleLogout(); setIsMenuOpen(false) }} className="pointer" style={{ cursor: 'pointer' }}>Logout</span>
                </li>
              </>
            )}
            <li className="d-lg-none">
              <Link to="/book-tour" onClick={() => setIsMenuOpen(false)} className="btn-book">Book a Tour</Link>
            </li>
          </ul>
        </nav>

        {/* Center: Logo */}
        <div className="logo-wrapper">
          <Link to="/" className="logo">ELEVÉ</Link>
        </div>

        {/* Right: Auth & CTA */}
        <div className="header-actions d-flex align-items-center gap-3">
          {!currentUser ? (
            <div className="auth-buttons d-none d-lg-flex align-items-center gap-3">
              <Link to="/login" className="nav-link pointer">Sign In</Link>
            </div>
          ) : (
            <div className="user-profile d-none d-lg-flex align-items-center gap-2">
              <Link to="/profile" style={{ display: 'flex', alignItems: 'center', gap: '8px', textDecoration: 'none', color: 'inherit' }}>
                <img src={currentUser.avatar} alt="User" className="avatar" />
                <span className="username">{currentUser.name}</span>
              </Link>
              <button onClick={handleLogout} className="btn-logout" aria-label="Logout">
                <i className="bi bi-box-arrow-right"></i>
              </button>
            </div>
          )}

          <Link to="/book-tour" className="btn-book text-decoration-none d-none d-lg-inline-block">Book a Tour</Link>

          {/* Mobile Burger */}
          <button
            className={`burger d-lg-none${isMenuOpen ? ' open' : ''}`}
            onClick={() => setIsMenuOpen(v => !v)}
            aria-label="Toggle menu"
          >
            <span></span>
            <span></span>
            <span></span>
          </button>
        </div>

      </div>
    </header>
  )
}
