// src/pages/Home/Home.jsx
import { useState, useEffect, useRef } from 'react'
import { Link } from 'react-router-dom'
import Hero from '../../components/Hero/Hero.jsx'
import { getTopDestinations } from '../../data/destinations.js'
import './Home.css'

export default function Home() {
  const topDestinations = getTopDestinations(6)
  const [activeIndex, setActiveIndex] = useState(0)
  const autoScrollRef = useRef(null)

  const nextSlide = () => {
    setActiveIndex(i => (i + 1) % topDestinations.length)
  }

  const prevSlide = () => {
    setActiveIndex(i => (i === 0 ? topDestinations.length - 1 : i - 1))
    resetAutoScroll()
  }

  const handleSetActive = (i) => {
    setActiveIndex(i)
    resetAutoScroll()
  }

  const startAutoScroll = () => {
    autoScrollRef.current = setInterval(() => {
      setActiveIndex(i => (i + 1) % topDestinations.length)
    }, 3000)
  }

  const stopAutoScroll = () => {
    if (autoScrollRef.current) {
      clearInterval(autoScrollRef.current)
      autoScrollRef.current = null
    }
  }

  const resetAutoScroll = () => {
    stopAutoScroll()
    startAutoScroll()
  }

  useEffect(() => {
    startAutoScroll()
    return () => stopAutoScroll()
  }, [])

  const getCardClass = (i) => {
    const len = topDestinations.length
    if (i === activeIndex) return 'carousel-card active'
    if (i === (activeIndex === 0 ? len - 1 : activeIndex - 1)) return 'carousel-card prev'
    if (i === (activeIndex === len - 1 ? 0 : activeIndex + 1)) return 'carousel-card next'
    return 'carousel-card'
  }

  return (
    <>
      <Hero />

      {/* Curated Experiences */}
      <section className="py-5 container">
        <div className="text-center mb-5">
          <h2 className="section-title">Curated Experiences</h2>
          <div className="accent-line"></div>
        </div>

        <div className="row g-4">
          {[
            { title: 'Natural Wonders', desc: "Immerse yourself in the untamed beauty of the world's most stunning landscapes." },
            { title: 'Cultural Heritage', desc: 'Journey through history and witness the rich traditions of diverse civilizations.' },
            { title: 'Urban Escapes', desc: 'Experience the vibrant energy and sophisticated allure of global metropolises.' }
          ].map((exp) => (
            <div key={exp.title} className="col-lg-4 col-md-6">
              <div className="exp-card h-100">
                <div className="exp-info">
                  <h3>{exp.title}</h3>
                  <p>{exp.desc}</p>
                  <Link to="/activities" className="btn-text text-uppercase">Explore →</Link>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Top Destinations */}
      <section className="top-destinations-section py-5 position-relative overflow-hidden">
        <div className="animated-bg"></div>
        <div className="container position-relative z-1">
          <div className="text-center mb-5">
            <h2 className="section-title">Top Destinations</h2>
            <div className="accent-line"></div>
          </div>

          <div className="carousel-container d-flex align-items-center justify-content-center perspective-1000">
            {topDestinations.map((dest, i) => (
              <div
                key={dest.id}
                className={getCardClass(i)}
                onClick={() => handleSetActive(i)}
              >
                <div className="card-content" onClick={() => window.location.href = `/destinations/${dest.id}`} style={{ cursor: 'pointer' }}>
                  <img src={dest.imageUrl} alt={dest.name} className="card-img" />
                  <div className="card-overlay">
                    <h3>{dest.name}</h3>
                    <p className="mb-0"><i className="bi bi-geo-alt-fill me-1"></i>{dest.location}</p>
                    {i === activeIndex && (
                      <div className="rating mt-2">
                        <i className="bi bi-star-fill"></i> {dest.rating}
                      </div>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Navigation Controls */}
          <div className="d-flex justify-content-center gap-3 mt-4">
            <button className="carousel-control-btn" onClick={prevSlide} aria-label="Previous destination">
              <i className="bi bi-chevron-left"></i>
            </button>
            <button className="carousel-control-btn" onClick={nextSlide} aria-label="Next destination">
              <i className="bi bi-chevron-right"></i>
            </button>
          </div>
        </div>
      </section>

      {/* Banner */}
      <section className="banner-section py-5">
        <div className="container text-center">
          <h2 className="banner-title mb-4">Ready for your next journey?</h2>
          <Link to="/book-tour" className="btn btn-outline" style={{ borderColor: 'var(--accent)', color: 'var(--accent)' }}>
            Get in Touch
          </Link>
        </div>
      </section>
    </>
  )
}

// src/app/pages/home/home.component.ts
import { Component, ChangeDetectionStrategy, OnInit, OnDestroy, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { HeroComponent } from '../../components/hero/hero.component';
import { Destination } from '../destinations/destination.model';
import { DestinationsService } from '../destinations/destinations.service';
import { Subject, Subscription, interval } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

@Component({
  selector: 'app-home',
  imports: [CommonModule, RouterLink, HeroComponent],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class HomeComponent implements OnInit, OnDestroy {
  topDestinations = signal<Destination[]>([]);
  activeIndex = signal<number>(0);
  private destroy$ = new Subject<void>();
  private autoScrollSubscription?: Subscription;

  constructor(private destinationsService: DestinationsService) { }

  ngOnInit() {
    this.destinationsService.getTopDestinations().subscribe(destinations => {
      this.topDestinations.set(destinations);
      this.startAutoScroll();
    });
  }

  ngOnDestroy() {
    this.stopAutoScroll();
    this.destroy$.next();
    this.destroy$.complete();
  }

  startAutoScroll() {
    this.stopAutoScroll();
    // Emit every 3 seconds (2.5s view + 0.5s pause/transition)
    this.autoScrollSubscription = interval(3000).pipe(
      takeUntil(this.destroy$)
    ).subscribe(() => {
      this.nextSlide();
    });
  }

  stopAutoScroll() {
    if (this.autoScrollSubscription) {
      this.autoScrollSubscription.unsubscribe();
    }
  }

  nextSlide() {
    this.activeIndex.update(index => (index + 1) % this.topDestinations().length);
  }

  prevSlide() {
    this.activeIndex.update(index =>
      index === 0 ? this.topDestinations().length - 1 : index - 1
    );
    this.resetAutoScroll();
  }

  setActiveIndex(index: number) {
    this.activeIndex.set(index);
    this.resetAutoScroll();
  }

  resetAutoScroll() {
    this.stopAutoScroll();
    this.startAutoScroll();
  }
}

<app-hero></app-hero>

<section class="py-5 container">
    <div class="text-center mb-5">
        <h2 class="section-title">Curated Experiences</h2>
        <div class="accent-line"></div>
    </div>

    <div class="row g-4">
        <div class="col-lg-4 col-md-6">
            <div class="exp-card h-100">
                <div class="exp-info">
                    <h3>Natural Wonders</h3>
                    <p>Immerse yourself in the untamed beauty of the world's most stunning landscapes.</p>
                    <a routerLink="/activities" class="btn-text text-uppercase">Explore →</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="exp-card h-100">
                <div class="exp-info">
                    <h3>Cultural Heritage</h3>
                    <p>Journey through history and witness the rich traditions of diverse civilizations.</p>
                    <a routerLink="/activities" class="btn-text text-uppercase">Explore →</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="exp-card h-100">
                <div class="exp-info">
                    <h3>Urban Escapes</h3>
                    <p>Experience the vibrant energy and sophisticated allure of global metropolises.</p>
                    <a routerLink="/activities" class="btn-text text-uppercase">Explore →</a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="top-destinations-section py-5 position-relative overflow-hidden">
    <div class="animated-bg"></div>
    <div class="container position-relative z-1">
        <div class="text-center mb-5">
            <h2 class="section-title text-white">Top Destinations</h2>
            <div class="accent-line bg-white"></div>
        </div>

        <div class="carousel-container d-flex align-items-center justify-content-center perspective-1000">
            @for (dest of topDestinations(); track dest.id; let i = $index) {
            <div class="carousel-card" [class.active]="i === activeIndex()"
                [class.prev]="i === (activeIndex() === 0 ? topDestinations().length - 1 : activeIndex() - 1)"
                [class.next]="i === (activeIndex() === topDestinations().length - 1 ? 0 : activeIndex() + 1)"
                (click)="setActiveIndex(i)">

                <div class="card-content" [routerLink]="['/destinations', dest.id]">
                    <img [src]="dest.imageUrl" [alt]="dest.name" class="card-img">
                    <div class="card-overlay">
                        <h3>{{ dest.name }}</h3>
                        <p class="mb-0"><i class="bi bi-geo-alt-fill me-1"></i> {{ dest.location }}</p>
                        @if (i === activeIndex()) {
                        <div class="rating mt-2">
                            <i class="bi bi-star-fill text-warning"></i> {{ dest.rating }}
                        </div>
                        }
                    </div>
                </div>
            </div>
            }
        </div>

        <!-- Navigation Controls -->
        <div class="d-flex justify-content-center gap-3 mt-4">
            <button class="btn btn-outline-light rounded-circle p-2" (click)="prevSlide()">
                <i class="bi bi-chevron-left"></i>
            </button>
            <button class="btn btn-outline-light rounded-circle p-2" (click)="nextSlide()">
                <i class="bi bi-chevron-right"></i>
            </button>
        </div>
    </div>
</section>

<section class="banner-section py-5">
    <div class="container text-center">
        <h2 class="banner-title mb-4">Ready for your next journey?</h2>
        <a routerLink="/book-tour" class="btn btn-outline"
            style="border-color: var(--accent); color: var(--accent);">Get in Touch</a>
    </div>
</section>
